<div class="form-group"> 
    <input type="hidden" id="restaurantID" name="restaurantID" value="<?php echo isset($restaurantID) ? $restaurantID : '0'; ?>">
    <label for="memName">Tên đầy đủ</label>
    <input type="text" class="form-control" value="<?php echo isset($nameRe) ? $nameRe : ''; ?>" id="nameRe"  name="nameRe"> 
</div>
<div class="form-group"> 
    <label for="userName">Tên đăng nhập</label>
    <input type="text" class="form-control" id="phoneRe"  name="phoneRe"  value="<?php echo isset($phoneRe) ? $phoneRe : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">Email</label>
    <input type="text" class="form-control" id="userMail"  name="userMail"  value="<?php echo isset($userMail) ? $userMail : ''; ?>"> 
</div>    
<div class="form-group"> 
    <label for="userMail">favouriteFood</label>
    <input type="text" class="form-control" id="favouriteFood"  name="favouriteFood"  value="<?php echo isset($favouriteFood) ? $favouriteFood : ''; ?>"> 
</div>     
<div class="form-group"> 
    <label for="userMail">spaceRes</label>
    <input type="text" class="form-control" id="spaceRes"  name="spaceRes"  value="<?php echo isset($spaceRes) ? $spaceRes : ''; ?>"> 
</div>       
<div class="form-group"> 
    <label for="userMail">carParkingRes</label>
    <input type="text" class="form-control" id="carParkingRes"  name="carParkingRes"  value="<?php echo isset($carParkingRes) ? $carParkingRes : ''; ?>"> 
</div>   
<div class="form-group"> 
    <label for="userMail">otherPoints</label>
    <input type="text" class="form-control" id="otherPoints"  name="otherPoints"  value="<?php echo isset($otherPoints) ? $otherPoints : ''; ?>"> 
</div> 
<div class="form-group"> 
    <label for="userMail">openTimeRe</label>
    <input type="text" class="form-control" id="openTimeRe"  name="openTimeRe"  value="<?php echo isset($openTimeRe) ? $openTimeRe : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">closeTimeRe</label>
    <input type="text" class="form-control" id="closeTimeRe"  name="closeTimeRe"  value="<?php echo isset($closeTimeRe) ? $closeTimeRe : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">latitudeRe</label>
    <input type="text" class="form-control" id="latitudeRe"  name="latitudeRe"  value="<?php echo isset($latitudeRe) ? $latitudeRe : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">latitudeRe</label>
    <input type="text" class="form-control" id="longitudeRe"  name="longitudeRe"  value="<?php echo isset($longitudeRe) ? $longitudeRe : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">latitudeRe</label>
    <input type="text" class="form-control" id="rateRe"  name="rateRe"  value="<?php echo isset($rateRe) ? $rateRe : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">minPrice</label>
    <input type="text" class="form-control" id="minPrice"  name="minPrice"  value="<?php echo isset($minPrice) ? $minPrice : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">maxPrice</label>
    <input type="text" class="form-control" id="maxPrice"  name="maxPrice"  value="<?php echo isset($maxPrice) ? $maxPrice : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">discount</label>
    <input type="text" class="form-control" id="discount"  name="discount"  value="<?php echo isset($discount) ? $discount : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">quantityBooking</label>
    <input type="text" class="form-control" id="quantityBooking"  name="quantityBooking"  value="<?php echo isset($quantityBooking) ? $quantityBooking : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">dateCreateRe</label>
    <input type="text" class="form-control" id="dateCreateRe"  name="dateCreateRe"  value="<?php echo isset($dateCreateRe) ? $dateCreateRe : ''; ?>"> 
</div>
<div class="form-group"> 
    <label for="userMail">dateCreateRe</label>
    <input type="text" class="form-control" id="dateCreateRe"  name="dateCreateRe"  value="<?php echo isset($dateCreateRe) ? $dateCreateRe : ''; ?>"> 
</div>

<div class="form-group"> 
    <label for="addressID">Địa chỉ</label> 
    <select id="addressID" name="addressID" class="form-control">        
      <option id="" value="0" selected="selected">--chọn địa chỉ--</option>  
      <?php foreach($address as $adr){?>
         <option id="<?php echo $adr->addressID; ?>" value="<?php echo $adr->addressID; ?>" <?php if(isset($addressID) && $addressID == $adr->addressID){ echo 'selected="selected"';} else {echo '';} ?> ><?php echo $adr->address; ?></option>
      <?php } ?>
    </select>
</div>      
<div class="form-group"> 
    <label for="addressID">Người dùng</label> 
    <select id="userID" name="userID" class="form-control">        
      <option id="" value="0" selected="selected">--chọn người dùng--</option>  
      <?php foreach($users as $item){?>
         <option id="<?php echo $item->userID; ?>" value="<?php echo $item->userID; ?>" <?php if(isset($userID) && $userID == $item->userID){ echo 'selected="selected"';} else {echo '';} ?> >
         <?php echo $item->memName.' ('.$item->userName.')' ?>
         </option>
      <?php } ?>
    </select>
</div>
<div class="form-group">                                                                                                                                
      <div class="checkbox">
        <label>
          <input type="checkbox" name="isDepositBo" id="isDepositBo" <?php echo (isset($isDepositBo) && $isDepositBo == 1) ? 'checked': ''; ?>>isDepositBo
        </label>
      </div>
</div>
<div class="form-group">                                                                                                                                
      <div class="checkbox">
        <label>
          <input type="checkbox" name="isDeactivate" id="isDeactivate" <?php echo (isset($isDeactivate) && $isDeactivate == 1) ? 'checked': ''; ?>>isDeactivate
        </label>
      </div>
</div>
<div class="form-group">                                                                                                                                
      <div class="checkbox">
        <label>
          <input type="checkbox" name="statusRes" id="statusRes" <?php echo (isset($statusRes) && $statusRes == 1) ? 'checked': ''; ?>>statusRes
        </label>
      </div>
</div>