<!DOCTYPE html>
<html lang="vi-VN">
<head>
<?php
    $title = isset($title) ? $title : 'Ăn Gì - Admin';
?>
    <title><?php echo $title; ?></title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="<?php echo base_url()?>resource/font-awesome-4.6.3/css/font-awesome.css">
    <link rel="stylesheet" href="<?php echo base_url()?>resource/bootstrap-3.3.6-dist/css/bootstrap.min.css">
 	<link rel="stylesheet" href="<?php echo base_url()?>resource/chosen_v1.6.2/chosen.css">    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">    
    <link rel = "stylesheet" type = "text/css" href = "<?php echo base_url()?>css/admin.css">  
    <link rel = "stylesheet" type = "text/css" href = "<?php echo base_url()?>resource/bootstrap-3.3.6-dist/plugins/datepicker/bootstrap-datetimepicker.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="<?php echo base_url()?>resource/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>
	<script src="<?php echo base_url()?>resource/chosen_v1.6.2/chosen.jquery.min.js"></script>
    <script src="<?php echo base_url()?>resource/bootstrap-3.3.6-dist/plugins/moment-with-locales.js"></script>
    <script src="<?php echo base_url()?>resource/bootstrap-3.3.6-dist/plugins/datepicker/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="<?=base_url()?>resource/tiny_mce/general.js"></script>
    <script type="text/javascript" src="<?=base_url()?>resource/tiny_mce/tiny_mce.js"></script>  
    <script type="text/javascript" src="<?=base_url()?>resource/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="<?=base_url()?>resource/ckfinder/ckfinder.js"></script>
    <script type="text/javascript" src="<?=base_url()?>resource/ckeditor/lang/vi.js"></script>
    <script src="<?php echo base_url()?>js/adminjs.js"></script>
</head>

<body>

<div class="main-body">

    <div class="sidebar col-md-2">
        <?php $this->load->view('admin/layout/sidebar.phtml', $user) ?>
    </div>

    <div class="content col-lg-10">
        <?php $this->load->view($content, $model) ?>
    </div>
</div>
       
</body>
</html>

