<div class="form-group">
    <div class="col-lg-6"> 
        <label for="categoryOfResID">Loại hình ẩm thực:</label> 
        <select id="categoryOfResID" name="categoryOfResID" class="form-control">        
          <option id="" value="" selected="selected">--chọn loại nhà hàng--</option>  
          <?php foreach($categories as $item){?>
             <option id="<?php echo $item->categoryOfResID; ?>" value="<?php echo $item->categoryOfResID; ?>" <?php if(isset($categoryOfResID) && $categoryOfResID == $item->categoryOfResID){ echo 'selected="selected"';} else {echo '';} ?> >
             <?php echo $item->nameCOR; ?>
             </option>
          <?php } ?>
        </select>
    </div>   
    <div class="col-lg-6">
        <input type="hidden" id="restaurantID" name="restaurantID" value="<?php echo isset($restaurantID) ? $restaurantID : '0'; ?>">
        <input type="hidden" id="userID" name="userID" value="<?php echo isset($userID) ? $userID : '0'; ?>">
        <label for="memName">Tên nhà hàng:</label>
        <input type="text" class="form-control" value="<?php echo isset($nameRe) ? $nameRe : ''; ?>" id="nameRe"  name="nameRe"> 
    </div> 
    <div class="col-lg-6">
        <label for="userName">Điện thoại:</label>
        <input type="text" class="form-control" id="phoneRe"  name="phoneRe"  value="<?php echo isset($phoneRe) ? $phoneRe : ''; ?>"> 
    </div>   
    <div class="col-lg-6"> 
    <label for="favouriteFood">Món đặc sắc:</label>
    <input type="text" class="form-control" id="favouriteFood"  name="favouriteFood"  value="<?php echo isset($favouriteFood) ? $favouriteFood : ''; ?>"> 
    </div>     
    <div class="col-lg-6"> 
        <label for="spaceRes">Không gian:</label>
        <input type="text" class="form-control" id="spaceRes"  name="spaceRes"  value="<?php echo isset($spaceRes) ? $spaceRes : ''; ?>"> 
    </div>       
    <div class="col-lg-6"> 
        <label for="carParkingRes">Chỗ để ô tô</label>
        <input type="text" class="form-control" id="carParkingRes"  name="carParkingRes"  value="<?php echo isset($carParkingRes) ? $carParkingRes : ''; ?>"> 
    </div>  
    <div class="col-lg-4"> 
        <label for="openTimeRe">Giờ mở của</label>
        <input placeholder="Giờ" id="openTimeRe" name="openTimeRe" class="form-control" type="text" onfocus="(this.type='time')" onblur="(this.type='text')" value="<?php echo isset($openTimeRe) ? $openTimeRe : ''; ?>">
    </div>
    <div class="col-lg-4"> 
        <label for="closeTimeRe">Giờ đóng cửa</label>
        <input placeholder="Giờ" id="closeTimeRe" name="closeTimeRe" class="form-control" type="text" onfocus="(this.type='time')" onblur="(this.type='text')" value="<?php echo isset($closeTimeRe) ? $closeTimeRe : ''; ?>">
     
    </div>      
    <div class="col-lg-4"> 
        <label for="rateRe">rateRe</label>
        <select disabled="disabled" id="rateRe" name="rateRe" class="form-control">
            <option id="0" value="0" <?php if(isset($rateRe) && $rateRe == 0){ echo 'selected="selected"';} else {echo '';} ?> >0 *</option>
            <option id="1" value="1" <?php if(isset($rateRe) && $rateRe == 1){ echo 'selected="selected"';} else {echo '';} ?> >1 *</option>
            <option id="2" value="2" <?php if(isset($rateRe) && $rateRe == 2){ echo 'selected="selected"'; } else {echo '';} ?>>2 *</option>
            <option id="3" value="3" <?php if(isset($rateRe) && $rateRe == 3){ echo 'selected="selected"'; } else {echo '';} ?>>3 *</option>
            <option id="4" value="4" <?php if(isset($rateRe) && $rateRe == 4){ echo 'selected="selected"'; } else {echo '';} ?>>4 *</option>
            <option id="5" value="5" <?php if(isset($rateRe) && $rateRe == 5){ echo 'selected="selected"'; } else {echo '';} ?>>5 *</option>
        </select>
    </div>  
    <div class="col-lg-4">                                                                                                                                
          <div class="checkbox">
            <label>
              <input type="checkbox" name="isDepositBo" id="isDepositBo" <?php echo (isset($isDepositBo) && $isDepositBo) ? 'checked': ''; ?>>isDepositBo
            </label>
          </div>
    </div>
    <div class="col-lg-4">                                                                                                                                
          <div class="checkbox">
            <label>
              <input type="checkbox" namename="isDeactivate" id="isDeactivate" <?php echo (isset($isDeactivate) && $isDeactivate) ? 'checked': ''; ?>>Dừng hoạt động
            </label>
          </div>
    </div>
    <div class="col-lg-4">                                                                                                                                
          <div class="checkbox">
            <label>
              <input type="checkbox" disabled="disabled" namename="statusRes" id="statusRes" <?php echo (isset($statusRes) && $statusRes) ? 'checked': ''; ?>>statusRes
            </label>
          </div>
    </div>
</div>  
<script type="">
    $('.datepicker').datetimepicker({locale: 'vi'});
    $('.time').datetimepicker({locale: 'vi',format: 'hh:mm'});
    $(document).ready(function(){
        var ok = '<?php echo isset($ok) ? $ok : ''; ?>';
        if (ok == '1')
        {
            setTimeout(function(){
                location.href = '<?php echo base_url().'user_profile/restaurant_edit'; ?>';    
            }, 2000)                                                                       
        }
    })
</script>