
<div class="form-group">   
    <div class="col-lg-3"> 
        <label for="minPrice">minPrice</label>
        <input type="text" class="form-control" id="minPrice"  name="minPrice"  value="<?php echo isset($minPrice) ? $minPrice : ''; ?>"> 
    </div>
    <div class="col-lg-3"> 
        <label for="maxPrice">maxPrice</label>
        <input type="text" class="form-control" id="maxPrice"  name="maxPrice"  value="<?php echo isset($maxPrice) ? $maxPrice : ''; ?>"> 
    </div>   
    <div class="col-lg-3"> 
        <label for="discount">discount</label>
        <input type="text" class="form-control" id="discount"  name="discount"  value="<?php echo isset($discount) ? $discount : ''; ?>"> 
    </div>
    <div class="col-lg-3"> 
        <label for="quantityBooking">quantityBooking</label>
        <input type="text" class="form-control" id="quantityBooking"  name="quantityBooking"  value="<?php echo isset($quantityBooking) ? $quantityBooking : ''; ?>"> 
    </div> 
</div>       