<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="topdisplay-item" style="display: table">
            <div class="title-content">
                <div class="title-row">
                    <div class="col-md-12">
                        <h3>14 kết quả tìm kiếm cho "ăn"</h3>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>
            </div>

            <div class="sidebar col-md-2">
                <div class="sidebar-content">
                    <h4>Danh mục</h4>
                    <ul class="sidebar-list">
                        <li><a href="">Nhà hàng</a></li>
                        <li><a href="">Buffet</a></li>
                        <li><a href="">Lẩu & Nướng</a></li>
                        <li><a href="">Hải sản</a></li>
                        <li><a href="">Nhật - Hàn</a></li>
                        <li><a href="">Ăn nhậu</a></li>
                    </ul>
                </div>

                <div class="sidebar-content">
                    <h4>Quận/Huyện</h4>
                    <ul class="sidebar-list">
                        <li><a href="">Ba Đình</a></li>
                        <li><a href="">Hoàn Kiếm</a></li>
                        <li><a href="">Thanh Xuân</a></li>
                        <li><a href="">Hai Bà Trưng</a></li>
                        <li><a href="">Đống Đa</a></li>
                        <li><a href="">Cầu Giấy</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-10">
                <ul class="item-content item-cat">
                    <?php
                    for($i=0; $i<20; $i++){
                        ?>
                        <li class="col-md-3">
                            <a style="display: block; position: relative" class="img-item" href="">
                                <img src="http://cdn.pasgo.vn/anh-diem-den/nha-hang-ao-quan-ngo-19-dong-tac-avatarjpg-5138.jpg">
                                <div class="item-infor">
                                    <label class="item-name item-name-sm">Ao quán</label>
                                <span class="rate-star">
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star" aria-hidden="true"></i>
                                </span>
                                <span class="rate-dollar">
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                </span>
                                    <label class="item-address item-address-sm">18 Ngõ 19 Đông Tác, Quận Đống Đa</label>
                                </div>
                            </a>

                            <div class="category-itemdetail" style="border: 1px solid #e0e0e0; text-align: center">
                                <p class="sale-content">Giảm <strong>20%</strong></p>
                                <p class="quick-description">Gọi món Việt ba miền</p>
                                <button class="place">Đặt chỗ ngay</button>
                            </div>
                        </li>
                        <?php
                    }
                    ?>
                </ul>
            </div>
        </div>

        <div style="text-align: center">
            <ul class="pagination">
                <li><a href="">1</a></li>
                <li><a href="">2</a></li>
                <li><a href="">3</a></li>
                <li><a href="">4</a></li>
                <li><a href="">5</a></li>
            </ul>
        </div>
    </div>
</div>