<link rel="stylesheet" href="<?php echo base_url()?>css/user.css">

<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            <table class="profile-stt">
                <tr>
                    <td><img src="http://cdn.pasgo.vn/images/Profile/no_avatar.png"></td>
                    <td>
                        <p>ID ĂnGì: <strong>123</strong></p>
                        <p>ĐT: <strong>01646223394</strong></p>
                    </td>
                </tr>

                <tr>
                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
                    <td></td>
                </tr>
            </table>
            <ul class="profile-sidebar">
                <li><a href="../user_profile"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li class="active"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</li>
                <li><a href="../user_profile/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li><a href=""><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li><a href=""><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="../user_profile/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>
                <li><a><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
                <li><a><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Quản lý Banner</h1>

            <ul style="margin: 40px 0">
                <?php
                for($i=0; $i<6; $i++){
                ?>
                    <li class="upload-banner">
                        <a>
                            <i class="fa fa-plus" aria-hidden="true"></i>
                            Thêm ảnh
                        </a>
                        <input class="" type="text" placeholder="Viết tiêu đề...">
                        <input type="text" placeholder="Viết mô tả...">
                    </li>
                <?php
                }
                ?>
                <li class="upload-banner">
                    <input type="submit" value="Cập nhật">
                </li>
            </ul>
        </div>
    </div>
</div>