<div class="panel panel-default">
  <!-- Default panel contents -->
    <div class="panel-heading">
        <h2><?php echo $title;?></h2>
    </div>
    <div class="panel-body">
        <a style="margin-bottom: 15px" class="btn btn-default" href="<?php echo base_url()?>admin/categories" role="button"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Quay về</a>

        <?php if($error!='' && $error!=null){?>
            <div class="bg-danger"><?php echo $error; ?></div>
        <?php }else if($success!='' && $success!=null){?>
            <div class="bg-success"><?php echo $success; ?></div>
        <?php }?>

        <form method="POST" action="">
            <div class="form-group">
                <label for="memName">Tên</label>
                <input type="text" class="form-control" value="<?php echo isset($nameCOR) ? $nameCOR : ''; ?>" id="nameCOR"  name="nameCOR" placeholder="">
            </div>
        	<div class="form-group">
                <label for="userName">Mô tả</label>
                <div>
                    <textarea id="desciptionCOR"  name="desciptionCOR"   class="form-control"><?php echo isset($desciptionCOR) ? $desciptionCOR : ''; ?></textarea>
                </div>
        	</div>
            <div class="form-group">
                  <div class="checkbox">
                    <label>
                      <input value="1" type="checkbox" name="statusCOR" id="statusCOR" <?php echo (isset($statusCOR) && $statusCOR == 1) ? 'checked': ''; ?>>Kích hoạt
                    </label>
                  </div>
            </div>
            <button name="submit" id="submit" class="btn btn-primary" value="save"><i class="fa fa-floppy-o" aria-hidden="true"></i> Lưu</button>

        </form>
  </div> 
</div>
  
<script>
    $(document).ready(function(){
        var ok = '<?php echo isset($ok) ? $ok : ''; ?>';
        if (ok == '1')
        {
            setTimeout(function(){
                location.href = '<?php echo base_url().'admin/categories'; ?>';
            }, 2000)
        }
    })
</script>