<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
      <h2><?php echo $title;?></h2>
  </div>
  <div class="panel-body">
      <a style="float: right; margin-bottom: 10px" class="btn btn-success btn-lg" href="<?php echo base_url()?>admin/add_news" role="button">
          <i class="fa fa-plus-circle" aria-hidden="true"></i> Thêm mới
      </a>
  <!-- Table -->
<table class="table table-bordered">
    <thead>
        <tr>
            <th class="text-center">ID</th>      
            <th class="text-center">Ảnh</th>      
            <th class="text-center">Loại</th>  
            <th>Tiêu đề</th>     
            <th class="text-center col-lg-2">Trạng thái</th>
            <th class="col-lg-2"></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($rows > 0){ ?>
        <?php foreach ($result as $item) {?>
        <tr>
            <td class="text-center"><?php echo $item->newsID; ?></td>   
            <td class="text-center"><img src="<?php echo base_url().$item->imageNews; ?>" alt="Ảnh tin tức" height="50px"></td>   
            <td class="text-center"><?php 
                switch ($item->typeNews){
                    case 31:
                        echo 'Tin cập nhật';
                        break;
                    case 32:
                        echo 'Sự kiện';
                        break; 
                    case 33:
                        echo 'Khuyến mãi';
                        break; 
                    case 34:
                        echo 'Trải nghiệm';
                        break; 
                }
            ?></td> 
            <td><?php echo $item->titleNews; ?></td>                                  
            <td class="text-center"><?php 
                switch ($item->statusNews){
                    case 0:
                        echo 'Chưa kích hoạt';
                        break;
                    case 1:
                        echo 'Đã kích hoạt';
                        break; 
                }
            ?></td>
            <td class="text-center">
            <a class="btn btn-info" href="<?php echo base_url()?>admin/edit_news/<?php echo $item->newsID; ?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Xem</a>
            <a class="btn btn-danger" onclick="return newsModule.delete('<?php echo $item->newsID; ?>');" href="<?php echo base_url()?>admin/delete_news/<?php echo $item->newsID; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i> Xóa</a>
            </td>
        </tr>
        <?php } ?>
        <?php } ?>
    </tbody>       
  </table>        
  <div class="row">
      <div class="col-lg-12">
        <?php echo $pagination; ?>
      </div>  
  </div>
  </div>
      
</div>
<script type="text/javascript">
    window.newsModule = window.newsModule || {};
    
    newsModule.delete = newsModule.delete || function(name){
        if (confirm('Xóa ' + name + '?'))
            return true;
        return false;
    }
</script>