<div class="container">
    <div class="row">

        <div class="topdisplay-item">
            <div class="title-content">
                <div class="title-row">
                    <div class="col-md-6">
                        <h3>điểm đến uy tín</h3>
                    </div>
                    <div class="col-md-6">
                        <a class="small-tit" href="">Xem tất cả <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>
            </div>

            <ul class="item-content">
                <?php
                $limit = 0;
                foreach ($topRating as $row) {
                    if ($limit == $limitRate) {
                        break;
                    }
                    ?>
                    <li class="col-md-3">
                        <a style="display: block; position: relative" class="img-item" href="">
                            <img src="<?php echo $row->addressImage; ?>">
                            <div class="item-infor">
                                <label class="item-name"><?php echo $row->nameRe; ?></label>
                                <span class="rate-star"><?php echo $row->average; ?><!-- fill in the star by rate value -->
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star" aria-hidden="true"></i>
                                </span>
                                <span class="rate-dollar">
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                </span>
                                <label class="item-address"><?php echo $row->address; ?></label>
                            </div>
                        </a>
                        <div style="border: 1px solid #e0e0e0; text-align: center">
                            <p class="sale-content">Giảm <strong><?php echo $row->discount; ?>%</strong></p>
                            <p class="quick-description"><?php echo $row->descriptionRes; ?></p>
                            <?php echo form_open('booking/reserve/' . $row->restaurantID); ?>
                            <input type="submit" class="place" value="Đặt chỗ ngay" />
                            <?php echo form_close(); ?> 
                        </div>
                    </li>
                    <?php
                    $limit++;
                }
                ?>
            </ul>
        </div>


        <div class="topdisplay-item">
            <div class="title-content">
                <div class="title-row">
                    <div class="col-md-6">
                        <h3>top ưu đãi</h3>
                    </div>
                    <div class="col-md-6">
                        <a class="small-tit" href="">Xem tất cả <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>
            </div>

            <ul class="item-content">
                <?php
                $limit = 0;
                foreach ($highestDiscount as $row) {
                    if ($limit == $limitDis) {
                        break;
                    }
                    ?>
                    <li class="col-md-3">
                        <a style="display: block; position: relative" class="img-item" href="">
                            <img src="<?php echo $row->addressImage; ?>">
                            <div class="item-infor">
                                <label class="item-name"><?php echo $row->nameRe; ?></label>
                                <span class="rate-star"><?php echo $row->average; ?><!-- fill in the star by rate value -->
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star" aria-hidden="true"></i>
                                </span>
                                <span class="rate-dollar">
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                </span>
                                <label class="item-address"><?php echo $row->address; ?></label>
                            </div>
                        </a>
                        <div style="border: 1px solid #e0e0e0; text-align: center">
                            <p class="sale-content">Giảm <strong><?php echo $row->discount; ?>%</strong></p>
                            <p class="quick-description"><?php echo $row->descriptionRes; ?></p>
                            <?php echo form_open('booking/reserve/' . $row->restaurantID); ?>
                            <input type="submit" class="place" value="Đặt chỗ ngay" />
                            <?php echo form_close(); ?> 
                        </div>
                    </li>
                    <?php
                    $limit ++;
                }
                ?>
            </ul>
        </div>




        <!--        hết hiển thị nhà hàng-->

        <div class="topdisplay-item">
            <div class="title-content">
                <div class="title-row">
                    <div class="col-md-6">
                        <h3>tin tức</h3>
                    </div>
                    <div class="col-md-6">
                        <a class="small-tit" href="" style="padding-left: 10px">Tất cả</a>
                        <a class="small-tit small-tit-news" href="">Cập nhật</a>
                        <a class="small-tit small-tit-news" href="">Sự kiện</a>
                        <a class="small-tit small-tit-news" href="">Khuyến mãi</a>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>
            </div>

            <ul class="item-content">
                <?php
                for ($i = 0; $i < 3; $i++) {
                    ?>
                    <li class="col-md-4">
                        <a style="display: block; position: relative" class="img-item" href="">
                            <img src="http://cdn.pasgo.vn/anh-tin-tuc-resize/400/pasgo-nang-cap-va-cau-chuyen-de-men-phieu-luu-ky-54.jpg">
                        </a>

                        <div style="text-align: center">
                            <h4 class="news-title"><a href="">Dế mèn phiêu lưu ký</a></h4>
                            <p class="news-desc">Một câu chuyện Dế mèn phiêu lưu ký của làng thương mại điện tử Việt Nam, không ngắn không dài nhưng vẫn đầy đủ các yếu tố...</p>
                        </div>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>
