<div class="container">
    <div class="row">

        <div class="topdisplay-item">
            <div class="title-content">
                <div class="title-row">
                    <div class="col-md-6">
                        <h3>điểm đến uy tín</h3>
                    </div>
                    <div class="col-md-6">
                        <a class="small-tit" href="">Xem tất cả <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>
            </div>

            <ul class="item-content">
                <?php
                for($i=0; $i<4; $i++){
                ?>
                    <li class="col-md-3">
                        <a style="display: block; position: relative" class="img-item" href="">
                            <img src="http://cdn.pasgo.vn/anh-diem-den/nha-hang-ao-quan-ngo-19-dong-tac-avatarjpg-5138.jpg">
                            <div class="item-infor">
                                <label class="item-name">Ao quán</label>
                                <span class="rate-star">
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star" aria-hidden="true"></i>
                                </span>
                                <label class="item-address">18 Ngõ 19 Đông Tác, Quận Đống Đa</label>
                            </div>
                        </a>

                        <div style="border: 1px solid #e0e0e0; text-align: center">
                            <p class="sale-content">Giảm <strong>20%</strong></p>
                            <p class="quick-description">Gọi món Việt ba miền</p>
                            <button class="place">Đặt chỗ ngay</button>
                        </div>
                    </li>
                <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>