<div class="restaurant-place shadow-outside">
    <p>Đặt chỗ trước khi đến</p>
    <form class="booking-res">
        <p>
            <input type="number" placeholder="Số người đến" min="1">
            <i class="fa fa-user" aria-hidden="true"></i>
        </p>

        <p>
            <input placeholder="Ngày" class="textbox-n" type="text" onfocus="(this.type='date')" onblur="(this.type='text')" id="date">
            <i class="fa fa-calendar" aria-hidden="true"></i>
        </p>

        <p>
            <input placeholder="Giờ" class="textbox-n" type="text" onfocus="(this.type='time')" onblur="(this.type='text')" id="date">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
        </p>

        <button>đặt chỗ ngay</button>
        <p>(Hoàn toàn không mất phí)</p>

        <span>Hoặc</span>
        <span>Gọi đến: <strong style="color: #d02028; font-size: 18px">1900 6005</strong> để đặt chỗ.</span>
    </form>
</div>