<link rel="stylesheet" href="<?php echo base_url() ?>css/user.css">


<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            <table class="profile-stt">
                <tr>
                    <td><img src="http://cdn.pasgo.vn/images/Profile/no_avatar.png"></td>
                    <td>
                        <p>ID ĂnGì: <strong>123</strong></p>
                        <p>ĐT: <strong>01646223394</strong></p>
                    </td>
                </tr>

                <tr>
                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
                    <td></td>
                </tr>
            </table>
            <ul class="profile-sidebar">
                <li><a href="<?php echo base_url() ?>user_profile"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li><a href="<?php echo base_url() ?>user_profile/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                <li><a href="<?php echo base_url() ?>user_profile/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li><a href="<?php echo base_url() ?>user_profile/restaurant_price"><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li><a href="<?php echo base_url() ?>CONTROLLERNAME/ACTION/ID"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="<?php echo base_url() ?>user_profile/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>
                <li class="active"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</li>
                <li><a><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Lịch sử đặt chỗ</h1>
            <ul class="history-booking">
                <?php
                foreach ($list as $row) {
                    echo '<li>';
                    echo '<a href = "" class = "booking-img">';
                    echo "<img src = '" . $row['addressImage'] . "' >";
                    echo '<p>' . $row['discount'] . '%</p>';
                    echo '</a>';
                    echo '<div class = "booking-restaurant-infor">';
                    echo '<a>' . $row['nameRe'] . '</a>';
                    echo '<p>' . $row['address'] . '</p>';
                    echo '<span style = "font-size: 18px">' . $row['avgRating'];
                    echo '<i class = "glyphicon glyphicon-star filled"></i>';
                    echo '<i class = "glyphicon glyphicon-star filled"></i>';
                    echo '<i class = "glyphicon glyphicon-star filled"></i>';
                    echo '<i class = "glyphicon glyphicon-star filled"></i>';
                    echo '<i class = "glyphicon glyphicon-star"></i>';
                    echo '</span>';
                    echo '<p>' . $row['campaign'] . '</p>';
                    echo '</div>';

                    echo '<div class = "booking-infor">';
                    echo '<p><span style="background-color:red;">NO TIME FIELD IN DB </span>[Thời gian: 18:00 | ' . $row['serveDate'] . '</p>';
                    echo '<p>Số người: ' . $row['quantityMember'] . '</p>';
                    echo '<button><i class = "fa fa-clock-o" aria-hidden = "true"></i>' . $row['statusText'] . '</button>';
                    echo '</div>';
                    echo '</li>';
                }
                ?>
            </ul>

        </div>
    </div>
</div>
