<link rel="stylesheet" href="<?php echo base_url()?>css/user.css">


<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            <table class="profile-stt">
                <tr>
                    <td><img src="http://cdn.pasgo.vn/images/Profile/no_avatar.png"></td>
                    <td>
                        <p>ID ĂnGì: <strong>123</strong></p>
                        <p>ĐT: <strong>01646223394</strong></p>
                    </td>
                </tr>

                <tr>
                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
                    <td></td>
                </tr>
            </table>
            <ul class="profile-sidebar">
                <li><a href="../user_profile"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li><a href="../user_profile/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                <li><a href="../user_profile/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li><a href="../user_profile/restaurant_price"><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li><a href="../booking/restaurant_manage_booking"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="../user_profile/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>
                <li class="active"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</li>
                <li><a><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Lịch sử đặt chỗ</h1>

            <ul class="history-booking">
                <li>
                    <a href="" class="booking-img">
                        <img src="http://cdn.pasgo.vn/anh-diem-den/sami-buffet-lau-nuong-nhat-ban-1-1926.jpg">
                        <p>30%</p>
                    </a>
                    <div class="booking-restaurant-infor">
                        <a>Sami</a>
                        <p>Royal City, Quận Thanh Xuân</p>
                        <span style="font-size: 18px">
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star"></i>
                        </span>
                        <p>Buffet lẩu nướng Nhật Bản</p>
                    </div>

                    <div class="booking-infor">
                        <p>Thời gian: 18:00 | 20/07/16</p>
                        <p>Số người: 22</p>
                        <button><i class="fa fa-clock-o" aria-hidden="true"></i> Đang chờ</button>
                    </div>
                </li>

                <li>
                    <a href="" class="booking-img">
                        <img src="http://cdn.pasgo.vn/anh-diem-den/sami-buffet-lau-nuong-nhat-ban-1-1926.jpg">
                        <p>30%</p>
                    </a>
                    <div class="booking-restaurant-infor">
                        <a>Sami</a>
                        <p>Royal City, Quận Thanh Xuân</p>
                        <span style="font-size: 18px">
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star filled"></i>
                            <i class="glyphicon glyphicon-star"></i>
                        </span>
                        <p>Buffet lẩu nướng Nhật Bản</p>
                    </div>

                    <div class="booking-infor">
                        <p>Thời gian: 18:00 | 20/07/16</p>
                        <p>Số người: 22</p>
                        <button><i class="fa fa-clock-o" aria-hidden="true"></i> Đang chờ</button>
                    </div>
                </li>
            </ul>

        </div>
    </div>
</div>