<h1 class="user-tit">Đổi mật khẩu</h1>

<?php if($error!='' && $error!=null){?>
    <div class="bg-danger"><?php echo $error; ?></div>
<?php }else if($success!='' && $success!=null){?>
    <div class="bg-success"><?php echo $success; ?></div>
<?php }?>


<form class="edit-user" method="POST">
    <ul>
        <li class="row">
            <label class="col-md-3 col-sm-3 col-xs-3">Mật khẩu cũ:</label>
            <input class="col-md-6 col-sm-9 col-xs-9" type="password" value="<?php echo isset($passwordOld) ? $passwordOld : ''; ?>" id="passwordOld"  name="passwordOld" placeholder="Mật khẩu cũ">
        </li>
        <li class="row">
            <label class="col-md-3 col-sm-3 col-xs-3">Mật khẩu mới:</label>
            <input class="col-md-6 col-sm-9 col-xs-9" type="password" id="password"  name="password"  value="<?php echo isset($password) ? $password : ''; ?>" placeholder="Mật khẩu mới">
        </li>  
        <li class="row">
            <label class="col-md-3 col-sm-3 col-xs-3">Nhập lại:</label>
            <input class="col-md-6 col-sm-9 col-xs-9" type="password" id="passwordRe"  name="passwordRe"  value="" placeholder="Mật khẩu mới">
        </li>  
        <li class="row">
            <label class="col-md-3 col-sm-3 col-xs-3"></label>
            <input class="col-md-6 col-sm-9 col-xs-9" type="submit" name="submit" value="Cập nhật">
        </li>
    </ul>
</form>
<script type="">

</script>  