<div class="topheader" style="background: #d02028">
    <div class="container">
        <div class="row">
            <nav class="col-md-12 col-sm-12 navbar">
                <ul class="topbar">

                    <li class="top-home"><a href="<?php echo base_url(); ?>">Logo</a> </li>

                    <li>
                        <a href="">Ẩm thực</a>
                        <ul class="hover-menu">
<!--                             <li><a href="<?php echo base_url() ?>restaurant/category">Nhà hàng</a></li>
                            <li><a href="">Buffet</a></li>
                            <li><a href="">Lẩu & Nướng</a></li>
                            <li><a href="">Hải sản</a></li>
                            <li><a href="">Nhật - Hàn</a></li>
                            <li><a href="">Địa điểm nhậu</a></li> -->
                            <li><a href="<?php echo base_url(); ?>Category">Nhaa hang</a></li>
                            <?php
                            foreach ($categoriesData as $key => $row) {
                                ?>
                                <li><a href="<?php echo base_url(); ?>Category/index/1/<?php echo $row['categoryOfResID']; ?>"><?php echo $row['nameCOR']; ?></a></li>        
                                <?php
                            }
                            ?>
                        </ul>
                    </li>

                    <li>
                        <a href="">Tin tức</a>
                        <ul class="hover-menu">
                            <li><a href="">Tin cập nhật</a></li>
                            <li><a href="">Sự kiện</a></li>
                            <li><a href="">Kuyến mãi</a></li>
                            <li><a href="">Trải nghiệm</a></li>
                        </ul>
                    </li>

                    <li><a href="">Hướng Dẫn</a></li>

                    <li>
                        <a href="">Giới thiệu</a>
                        <ul class="hover-menu">
                            <li><a href="">Về chúng tôi</a></li>
                            <li><a href="">Đối tác</a></li>
                        </ul>
                    </li>

                    <li class="top-register">
                        <?php
                        $full = "Đăng nhập";
                        $isLogIn = false;
                        $isRestOwner = false;
                        if ($this->session->userdata("ID") != null) {
                            $lname = $this->session->userdata("lname");
                            $fname = $this->session->userdata("fname");
                            $full = $lname . " " . $fname;
                            $type = $this->session->userdata("Type");
                            if ($type == 2) {
                                $isRestOwner = true;
                            }
                            $isLogIn = true;
                        }
                        ?>   

                        <a href=""><?php echo $full; ?> <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                        <div class="hover-menu hover-signin">
                            <!-- if users have signed in -->
                            <?php if ($isLogIn == true) { ?>
                                <ul class="user-loged">
                                    <li><a href="<?php echo base_url(); ?>user"> Thông tin tài khoản</a></li>
                                    <li><a href="<?php echo base_url(); ?>user/change_Password"> Quản hlý mật khẩu</a></li>
                                    <li><a href="<?php echo base_url(); ?>booking/viewBooking "> Lịch sử đặt chỗ</a></li>
                                    <?php
                                    if ($isRestOwner) {
                                        echo '<li><a href="' . base_url('booking/manageReservation') . '"> Quản lý đặt chỗ</a></li>';
                                    }
                                    ?>
                                    <a href="<?php echo base_url(); ?>user/sign_out" style="margin: 8px 0" class="btn btn-info btn-lg">Đăng xuất</a>

                                </ul>

                                <!-- if users have not signed in      -->
                                <?php
                            } else {
                                ?>
                                <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal"><?php echo $full; ?></button>
                                <div class="hover-register">
                                    <label class="small-tit">Thành viên mới? <a href="<?php echo base_url(); ?>user/register">Đăng ký</a></label>
                                </div>
                                <?php
                            }
                            ?>
                        </div>

                        <!-- Modal -->
                        <?php $this->load->view('site/user/user/login.phtml'); ?>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

<div style="background: #f7f6f4">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <?php
                $attribute = array("class" => "search", "method" => "get");
                echo form_open('search/', $attribute);
                ?>
                <input type="text" name="userTerm" placeholder="Buffet, Lẩu & Nướng, Hải sản..." required="true">
                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                <?php echo form_close(); ?>
            </div>
        </div>
    </div>
</div>
</div>
<?php echo $this->session->flashdata('msg'); ?>
<div class="main-banner">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="http://demo.themeum.com/wordpress/cuisine/wp-content/uploads/2016/04/1.jpg">
                <div class="carousel-caption">
                    <h1>Ăn Gì</h1>
                    <h3>Trang web tìm kiếm phục vụ hàng triệu bữa ăn ngon</h3>
                </div>
            </div>

            <div class="item">
                <img src="http://demo.themeum.com/wordpress/cuisine/wp-content/uploads/2016/03/3-1.jpg">
            </div>

            <div class="item">
                <img src="http://demo.themeum.com/wordpress/cuisine/wp-content/uploads/2016/03/2-1.jpg">
            </div>

        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<script>

//    custom html5 error message for a required field

    $(document).ready(function () {
        var intputElements = document.getElementsByTagName("INPUT");
        for (var i = 0; i < intputElements.length; i++) {
            intputElements[i].oninvalid = function (e) {
                e.target.setCustomValidity("");
                if (!e.target.validity.valid) {
//                    if (e.target.name == "username") {
                    e.target.setCustomValidity("Please insert your keyword in the box");
//                    } else {
//                        e.target.setCustomValidity("The field 'Password' cannot be left blank");
//                    }
                }
            };
        }
    })
</script>