<div class="topheader" style="background: #d02028">
    <div class="container">
        <div class="row">
            <nav class="col-md-12 col-sm-12 navbar">
                <ul class="topbar">

                    <li class="top-home"><a href="">Logo</a> </li>

                    <li>
                        <a href="">Ẩm thực</a>
                        <ul class="hover-menu">
                            <li><a href="<?php echo base_url()?>restaurant/category">Nhà hàng</a></li>
                            <li><a href="">Buffet</a></li>
                            <li><a href="">Lẩu & Nướng</a></li>
                            <li><a href="">Hải sản</a></li>
                            <li><a href="">Nhật - Hàn</a></li>
                            <li><a href="">Địa điểm nhậu</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="">Tin tức</a>
                        <ul class="hover-menu">
                            <li><a href="">Tin cập nhật</a></li>
                            <li><a href="">Sự kiện</a></li>
                            <li><a href="">Kuyến mãi</a></li>
                            <li><a href="">Trải nghiệm</a></li>
                        </ul>
                    </li>

                    <li><a href="">Hướng Dẫn</a></li>

                    <li>
                        <a href="">Giới thiệu</a>
                        <ul class="hover-menu">
                            <li><a href="">Về chúng tôi</a></li>
                            <li><a href="">Đối tác</a></li>
                        </ul>
                    </li>

                    <li class="top-register">
                    <?php
                        if($this->session->userdata("ID") != null)
                        {
                            $lname = $this->session->userdata("lname");
                            $fname = $this->session->userdata("fname");
                            $Type = $this->session->userdata("Type");
                            $full = $lname." ".$fname
                            
                            ?>
                            
                            <a href=""><?php echo $full; ?> <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                            <div class="hover-menu hover-signin">
                                <ul class="user-loged">
                                    <li><a href="">Thông tin tài khoản</a></li>
                                    <li><a href="">Quản lý mật khẩu</a></li>
                                    <li><a href="">Lịch sử đặt chỗ</a></li>
                                    <button style="margin: 8px 0" type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Đăng xuất</button>
                                </ul>
                            </div>
                            <?php
                        }
                        else {
                       
                    ?>

                        <a href="">Đăng nhập <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                        <div class="hover-menu hover-signin">
                            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Đăng nhập</button>
                            <div class="hover-register">
                                <label class="small-tit">Thành viên mới? <a href="">Đăng ký</a></label>
                            </div>
                        </div>
                        <!-- Modal -->
                        <div class="modal fade" id="myModal" role="dialog">
                            <div class="modal-dialog">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Login</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form class="submit-form" action="user/login" method="post">
                                            <ul>
                                                <li>
                                                    <label>Số điện thoại</label>
                                                    <input type="text" name = "phone">
                                                </li>
                                                <li>
                                                    <label>Mật khẩu</label>
                                                    <input type="password" name = "password">
                                                </li>
                                                <li>
                                                    <label></label>
                                                    <button class="btn">Đăng nhập</button>
                                                </li>
                                            </ul>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <?php } ?>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

<div style="background: #f7f6f4">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <form class="search">
                    <input type="text" placeholder="Buffet, Lẩu & Nướng, Hải sản...">
                    <button><i class="fa fa-search" aria-hidden="true"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="main-banner">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="http://demo.themeum.com/wordpress/cuisine/wp-content/uploads/2016/04/1.jpg">
                <div class="carousel-caption">
                    <h1>Ăn Gì</h1>
                    <h3>Trang web tìm kiếm phục vụ hàng triệu bữa ăn ngon</h3>
                </div>
            </div>

            <div class="item">
                <img src="http://demo.themeum.com/wordpress/cuisine/wp-content/uploads/2016/03/3-1.jpg">
            </div>

            <div class="item">
                <img src="http://demo.themeum.com/wordpress/cuisine/wp-content/uploads/2016/03/2-1.jpg">
            </div>

        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
