<!DOCTYPE html>
<html lang="vi-VN">
<head>
    <title>Ăn Gì</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="<?php echo base_url(); ?>resource/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="<?php echo base_url(); ?>resource/bootstrap/css/bootstrap.min.css">
    <script src="<?php echo base_url(); ?>resource/jquery/dist/jquery.min.js"></script>
    <script src="<?php echo base_url(); ?>resource/bootstrap/js/bootstrap.min.js"></script>
    <script src="<?php echo base_url(); ?>js/script.js"></script>

    <link rel = "stylesheet" type = "text/css" href = "<?php echo base_url(); ?>css/style.css">

</head>

<body>

<div class="header">
    <?php $this->load->view('site/layout/header.phtml') ?>
</div>

<div class="content">
    <?php $this->load->view($content) ?>
</div>

<div class="footer">
    <?php $this->load->view('site/layout/footer.phtml') ?>
</div>


<div id="fb-root"></div>
<script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>