<!DOCTYPE html>
<html lang="vi-VN">
<head>
    <title>Ăn Gì</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="<?php echo base_url();?>bootstrap/bootstrap-3.3.6-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>bootstrap/font-awesome-4.6.3/css/font-awesome.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="<?php echo base_url();?>bootstrap/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script>

    <link rel = "stylesheet" type = "text/css" href = "<?php echo base_url();?>css/style.css">
</head>

<body>

<div class="header">
<?php $this->load->view('site/layout/header.phtml') ?>
</div>

<div class="content">
    <?php $this->load->view($content) ?>
</div>

<div class="footer">
<?php $this->load->view('site/layout/footer.phtml') ?>
</div>


</body>
</html>