<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <h3>Món đặc sắc</h3>
  </div>
  <div class="panel-body"> 
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 80px;" class="text-center">Ảnh</th>
                <th>Tên</th>
                <th class="text-center col-lg-2">Giá</th>
            </tr>
        </thead>
        <tbody>
            <?php if (isset($foods)){ ?>
            <?php foreach ($foods as $item) {?>
            <tr>
                <td class="text-center">
                <img src="<?php echo $item->imageIDSrc; ?>" id="imageIDSrc" alt="Ảnh món ăn" style="width: 80px; height: 80px;" class="img-thumbnail">
                 </td> 
                <td><?php echo $item->nameFo; ?></td>
                <td class="text-right"><?php echo $item->priceFo; ?></td> 
            </tr>
            <?php } ?>
            <?php } ?>
        </tbody>
    </table>
    </div>
</div>