<h1><?php echo $title; ?></h1>
<div class="bg-danger"><?php echo $error; ?></div>
<form class="edit-user" method="POST">
    <ul>
        <li>
            <label>Tên:</label> 
            <input type="text" value="<?php echo isset($memName) ? $memName : ''; ?>" id="memName"  name="memName" placeholder=""> 
        </li>
        <li>
            <label>Email:</label>              
            <input type="text" id="userMail"  name="userMail"  value="<?php echo isset($userMail) ? $userMail : ''; ?>" placeholder="Email"> 
        </li>
        <li>
            <label>Ngày sinh:</label> 
            <div  style="width:200px;display:inline-table;">
                <div class='input-group date datepicker'>
                    <input type="text" id="memBirthDay" style="width:100%;" name="memBirthDay"  value="<?php echo isset($memBirthDay) ? $memBirthDay : ''; ?>"> 
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>                 
            </div>                 
        </li>
        <li>
            <label for="memGender">Giới tính</label> 
            <div  style="width:200px;display:inline-table;">
                <select id="memGender" name="memGender" class="form-control">
                  <option id="0" value="0" <?php if(isset($memGender) && $memGender == '0'){ echo 'selected="selected"';} else {echo '';} ?> >Nữ</option>
                  <option id="1" value="1" <?php if(isset($memGender) && $memGender == '1'){ echo 'selected="selected"';} else {echo '';} ?> >Nam</option>
                  <option id="1" value="2" <?php if(isset($memGender) && $memGender == '2'){ echo 'selected="selected"'; } else {echo '';} ?>>Khác</option>
                </select>
            </div>
        </li>
        <li>
            <label></label>
            <input type="submit" name="submit" value="Cập nhật">
        </li>
    </ul>
</form>
<script type="">
    $(document).ready(function(){
        $('.datepicker').datetimepicker({locale: 'vi',format: 'DD/MM/YYYY'}); 
    }) 
</script>  