<?php
	$title = 'Add new blog';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
	$form->setAttribute('action', $this->url('angi', array('action' => 'add')));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('blog'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();

 ?>