<?php

$title = 'My blogs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('angi', array('action'=>'add'));?>">Add new blog</a>
</p>

<table class="table">
<tr>
    <th>ID</th>
    <th>Blog</th>
    <th>Created</th>
    <th> </th>
</tr>
<?php foreach ($blogs as $blog) : ?>
<tr>
    <td><?php echo $this->escapeHtml($blog->id);?></td>
    <td><?php echo $this->escapeHtml($blog->blog);?></td>
    <td><?php echo $this->escapeHtml($blog->created);?></td>
    <td>
        <a href="<?php echo $this->url('angi',
            array('action'=>'update', 'id' => $blog->id));?>">Update</a>
        <a href="<?php echo $this->url('angi',
            array('action'=>'delete', 'id' => $blog->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>