<link rel="stylesheet" href="<?php echo base_url()?>css/user.css">


<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            <table class="profile-stt">
                <tr>
                    <td><img src="http://cdn.pasgo.vn/images/Profile/no_avatar.png"></td>
                    <td>
                        <p>ID ĂnGì: <strong>123</strong></p>
                        <p>ĐT: <strong>01646223394</strong></p>
                    </td>
                </tr>

                <tr>
                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
                    <td></td>
                </tr>
            </table>
            <ul class="profile-sidebar">
                <li><a href="../user_profile"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li><a href="../user_profile/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                <li><a href="../user_profile/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li><a href="../user_profile/restaurant_price"><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li class="active"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</li>
                <li><a href="../user_profile/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>
                <li><a href="../booking/user_booking_history"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
                <li><a><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Lịch sử đặt chỗ</h1>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Ngày đặt chỗ</th>
                    <th>ID khách hàng</th>
                    <th>Số điện thoại</th>
                    <th>Số người</th>
                    <th>Thời gian</th>
                    <th>Tình trạng</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th>21/04/16</th>
                    <th>34567</th>
                    <th>01646223394</th>
                    <th>8</th>
                    <th>20:00 | 21/05/16</th>
                    <th>Đang chờ</th>
                </tr>

                <tr>
                    <th>21/04/16</th>
                    <th>34567</th>
                    <th>01646223394</th>
                    <th>8</th>
                    <th>20:00 | 21/05/16</th>
                    <th>Đang chờ</th>
                </tr>

                <tr>
                    <th>21/04/16</th>
                    <th>34567</th>
                    <th>01646223394</th>
                    <th>8</th>
                    <th>20:00 | 21/05/16</th>
                    <th>Đang chờ</th>
                </tr>
                </tbody>
            </table>


            <div class="statistic-book"></div>
        </div>
    </div>
</div>