<div class="container">
    <div class="row">
        <div class="col-md-4 footer-col">
            <p> Với công cụ tìm kiếm hàng trăm cửa hàng gần nhất,
                dịch vụ đặt chỗ online tiết kiệm tối ưu thời gian, Ăn gì ra đời nhằm  mang lại những tiện ích tối ưu cho khách hàng.
            Ăn Gì- Điểm đến tin cậy cho những bữa ăn ngon. </p>
        </div>

        <div class="col-md-3 footer-col">
            <ul>
                <li><a href="">CHÚNG TÔI</a> </li>
                <li><a href="">Quy chế hoạt động</a> </li>
                <li><a href="">Chính sách bảo mật</a> </li>
                <li><a href="">Cơ chế giải quyết</a> </li>
                <li><a href="">Đối tác</a> </li>
            </ul>
        </div>

        <div class="col-md-2 footer-col">
            <ul>
                <li><a>THAM GIA VỚI CHÚNG TÔI</a></li>
                <li>
                    <a class="social-logo" href="https://www.facebook.com/angivn.top">
                        <img src="http://cdn.pasgo.vn/images/Tintucs/facebook-PASGO.png">
                    </a>
                    <a class="social-logo" href="facebook.com">
                        <img src="http://cdn.pasgo.vn/images/Tintucs/Google-PASGO.png">
                    </a>
                    <a class="social-logo" href="facebook.com">
                        <img src="http://cdn.pasgo.vn/images/Tintucs/youtube-PASGO.png">
                    </a>
                </li>

            </ul>
        </div>
    </div>
</div>


<div id="fb-root"></div>