<div class="topheader" style="background: #d02028; height: 46px">
    <div class="container">
        <div class="row">

            <div class="col-md-2 col-sm-2" style="width: 122px">
                <a href="<?php echo base_url()?>" class="logo">
                    <img src="<?php echo base_url()?>img/logo.jpg">
                </a>
            </div>
            <div id="home-list-resp">
                <p class="tool-bar bar1"></p>
                <p class="tool-bar bar2"></p>
                <p class="tool-bar bar3"></p>
            </div>


            <nav class="col-md-12 col-sm-12 navbar">
                <ul class="topbar">  

                    <li>
                        <form class="R-search hidden-nav">
                            <button><i class="fa fa-search" aria-hidden="true"></i></button>
                            <input type="text" placeholder="Buffet, Lẩu & Nướng, Hải sản...">

                        </form>
                    </li>
                    <?php if ($user == ''){?>
                        <li>
                            <a class="hidden-nav" href="">Tài khoản</a>

                            <span class="cross-down">
                                <span class="bar4"></span>
                                <span class="bar5"></span>
                            </span>

                            <ul class="hover-menu">
                                <li><a href="javascript:;" data-toggle="modal" data-target="#myModal">Đăng nhập</a></li>
                                <li><a href="<?php echo base_url(); ?>home/signup">Đăng kí</a></li>
                            </ul>
                        </li>
                    <?php } else{?>
                        <li>
                            <a class="hidden-nav" href="javascript:;"><?php echo $fullname ?></a>
                            <span class="cross-down">
                                <span class="bar4"></span>
                                <span class="bar5"></span>
                            </span>

                            <ul class="hover-menu">
                                <li><a href="<?php echo base_url(); ?>user_profile">Thông tin cá nhân</a></li>
                                <?php if($level == 0){//người dùng thực khách ?>\
                                    <li><a href="<?php echo base_url(); ?>user_profile/user_manage_booking">Lịch sử đặt chỗ</a></li>
                                <?php } else  if($level == 1){//người dùng nhà hàng ?>
                                    <li><a href="<?php echo base_url(); ?>user_profile">Quản lý nhà hàng</a></li>
                                    <li><a href="<?php echo base_url(); ?>user_profile/restaurant_manage_booking">Quản lý đặt chỗ</a></li>
                                <?php }  else  if($level == 2){//admin ?>
                                    <li><a href="<?php echo base_url(); ?>admin"></i>Quản trị</a></li>
                                <?php } ?>
                                <li><a href="<?php echo base_url(); ?>home/logout">Đăng xuất</a></li>
                            </ul>
                        </li>
                    <?php }?>

                    <li>
                        <a href="javascript:;">Ẩm thực</a>

                        <?php if (isset($categoryModels)) {?>
                        <span class="cross-down">
                            <span class="bar4"></span>
                            <span class="bar5"></span>
                        </span>
                        <ul class="hover-menu">
							<?php foreach ($categoryModels as $item) {?>
                            <li><a href="<?php echo base_url().'home/category/'.$item->categoryOfResID ;?>"><?php echo $item->nameCOR;?></a></li> 
                            <?php } ?>
                        </ul>
                        <?php } ?>
                    </li>    
                    <li>
                        <a href="javascript:;">Tin tức</a>
                        <span class="cross-down">
                            <span class="bar4"></span>
                            <span class="bar5"></span>
                        </span>
                        <ul class="hover-menu">
                            <li><a href="<?php echo $this->uriutils->BuildMenuStaticUrl(31);?>">Tin cập nhật</a></li>
                            <li><a href="<?php echo $this->uriutils->BuildMenuStaticUrl(32);?>">Sự kiện</a></li>
                            <li><a href="<?php echo $this->uriutils->BuildMenuStaticUrl(33);?>">Khuyến mãi</a></li>
                            <li><a href="<?php echo $this->uriutils->BuildMenuStaticUrl(34);?>">Trải nghiệm</a></li>   
                        </ul>
                    </li>   
                    <li>
                        <a href="">Hướng Dẫn</a>
                        <span class="cross-down">
                            <span class="bar4"></span>
                            <span class="bar5"></span>
                        </span>
                        <ul class="hover-menu">
                            <li><a href="<?php echo base_url()?>new-details/2">Thực khách đặt chỗ</a></li>
                            <li><a href="<?php echo base_url()?>new-details/3">Quản lý nhà hàng</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo base_url()?>new-details/1">Giới thiệu</a>
                    </li>



                    <li class="top-register">
                        <?php if ($user == ''){
                         ?>
                        <a href="javascript:;">Đăng nhập <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                        <div class="hover-menu hover-signin">
                            <i class="fa fa-caret-up" aria-hidden="true"></i>
                            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Đăng nhập</button>
                            <div class="hover-register">
                                <label class="small-tit">Thành viên mới? <a href="<?php echo base_url(); ?>home/signup">Đăng ký</a></label>
                            </div>
                        </div>
                        <?php
                            }else {?>

                        <a href="javascript:;">Xin chào: <?php echo $fullname ?> <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                        <div class="hover-menu hover-signin">
                            <i class="fa fa-caret-up" aria-hidden="true"></i>
                            <a class="user-link" href="<?php echo base_url(); ?>user_profile"><i class="fa fa-caret-right" aria-hidden="true"></i> Thông tin cá nhân</a>
                            <?php if($level == 0){//người dùng thực khách ?>
                                <a class="user-link" href="<?php echo base_url(); ?>user_profile/user_manage_booking"><i class="fa fa-caret-right" aria-hidden="true"></i> Lịch sử đặt chỗ</a>
                            <?php } else  if($level == 1){//người dùng nhà hàng ?>
                                <a class="user-link" href="<?php echo base_url(); ?>user_profile/restaurant_edit"><i class="fa fa-caret-right" aria-hidden="true"></i> Quản lý nhà hàng</a>
                                <a class="user-link" href="<?php echo base_url(); ?>user_profile/restaurant_manage_booking"><i class="fa fa-caret-right" aria-hidden="true"></i> Quản lý đặt chỗ</a>
                            <?php }  else  if($level == 2){//admin ?>
                                <a class="user-link" href="<?php echo base_url(); ?>admin"><i class="fa fa-caret-right" aria-hidden="true"></i> Quản trị</a>
                            <?php } ?>
                            <a class="user-link" href="<?php echo base_url(); ?>home/logout"><i class="fa fa-caret-right" aria-hidden="true"></i> Đăng xuất</a>
                        </div>    
                        <?php } ?>
                        <!-- Modal -->
<!--                        --><?php //$this->load->view('site/user/user/login.phtml') ?>
                    </li>
                             
                </ul>
            </nav>
        </div>
    </div>
</div>

<div style="background: #f7f6f4">
    <div class="container">
        <div class="row">
            <div class="col-md-8"></div>
            <div class="col-md-4" style="height: 75px">
                <form class="search">
                    <button id="btnSearch"><i class="fa fa-search" aria-hidden="true"></i></button>
                    <input type="text" id="keyword" name="keyword" placeholder="Buffet, Lẩu & Nướng, Hải sản...">
                    <script type="text/javascript">
                           $(document).ready(function(){
                                $('#btnSearch').click(function(){   
                                    var url = '<?php echo base_url('home/search');?>' + '/0/0/' + encodeURIComponent($('#keyword').val());
                                    location.href = url;
                                    return false;
                                })
                           });
                    </script>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="main-banner">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<?php echo base_url()?>img/banner1.jpg">
                <div class="carousel-caption">
                    <h1>Ăn Gì</h1>
                    <h3>Trang web tìm kiếm phục vụ hàng triệu bữa ăn ngon</h3>
                </div>
            </div>

            <div class="item">
                <img src="<?php echo base_url()?>img/banner2.jpg">
            </div>

            <div class="item">
                <img src="<?php echo base_url()?>img/banner3.jpg">
            </div>

        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<?php $this->load->view('site/user/user/login.phtml') ?>