
<ul class="profile-sidebar">
    <div class="profile-stt">
        <div class="col-md-5 col-sm-5 col-xs-5" style="text-align: center;">
            <img id="imageIDSrc" alt src="<?php echo $addressImage!= '' ? base_url().$addressImage : base_url().'img/no-image.jpg'; ?>">
        </div>
        <div class="col-md-7 col-sm-7 col-xs-7">
            <p>Mã khách hàng: <strong><?php echo $userID; ?></strong></p>
            <p><strong><?php echo $memName; ?></strong></p>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <button onclick="return profileModule.openCkFinder();">Chọn ảnh</button>
            <button id="btnUpdateAvatar" style="display: none;" onclick="return profileModule.changeAvatar();">Lưu</button>
        </div>
    </div>
    <li class="active"><a href="<?php echo base_url()?>user_profile"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
    <?php if ($level == 1){ ?>
    <li><a href="<?php echo base_url()?>user_profile/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
    <li><a href="<?php echo base_url()?>user_profile/restaurant_edit"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
    <li><a href="<?php echo base_url()?>user_profile/restaurant_manage_booking"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
    <?php } ?>
    <li><a href="<?php echo base_url()?>user_profile/user_manage_booking"><i class="fa fa-clock-o" aria-hidden="true"></i></i> Lịch sử đặt chỗ</a></li>
    <li><a href="<?php echo base_url()?>user_profile/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>
    <li><a href="<?php echo base_url()?>home/logout"><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
</ul>
 <script type="text/javascript">
    window.profileModule = window.profileModule || {};   
    
    $(document).ready(function(){ 
    })
                
    profileModule.openCkFinder = profileModule.openCkFinder || function() { 
        CKFinder.popup( {
             chooseFiles: true,
             onInit: function( finder ) {
                 finder.on( 'files:choose', function( evt ) {
                     var file = evt.data.files.first();     
                     $('#imageIDSrc').attr('src', file.getUrl());
                     $('#btnUpdateAvatar').show();
                 } );
                 finder.on( 'file:choose:resizedImage', function( evt ) {   
                     $('#imageIDSrc').attr('src', evt.data.resizedUrl);
                     $('#btnUpdateAvatar').show();
                 } );
             }
         } );
    }
       
    profileModule.changeAvatar = profileModule.changeAvatar || function(){ 
        $.ajax({ 
           type : "POST",
           data : {                                         
               'addressImage' : $('.profile-stt #imageIDSrc').attr('src'),
           },
           dataType:'json',                                             
           url: '<?php echo base_url("user_profile/changeAvatar"); ?>', // target element(s) to be updated with server response 
           cache : false,
           //check this in firefox browser
           complete : function(response){ 
                var jsonData = $.parseJSON(response.responseText);
                if (jsonData.type == 'success'){ 
                    alert(jsonData.text);
                    $('#btnUpdateAvatar').hide();
                }
                else if (jsonData.type == 'error'){   
                    alert(jsonData.text);
                }
           }
        });        
        return false;
    }
    
</script>