<!DOCTYPE html>
<html>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <?php
                    $this->load->library('javascript');
                    ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>Đăng ký thành viên</h4>
                        </div>
                        <?php echo $this->session->flashdata('registerMsg'); ?>
                        <div class="panel-body">
                            <?php $attributes = array("name" => "registrationform");
                            echo form_open("user/register", $attributes);
                            ?>
                            <div class="form-group">
                                <label for="fname">Tên</label>
                                <input class="form-control" name="fname" placeholder="Your First Name" type="text" value="<?php echo set_value('fname'); ?>" />
                                <span class="text-danger"><?php echo form_error('fname'); ?></span>
                            </div>

                            <div class="form-group">
                                <label for="name">Họ</label>
                                <input class="form-control" name="lname" placeholder="Last Name" type="text" value="<?php echo set_value('lname'); ?>" />
                                <span class="text-danger"><?php echo form_error('lname'); ?></span>
                            </div>

                            <div class="form-group">
                                <label for="dob">Ngày sinh</label>

                                <input class="form-control" type="date" name="dob" value="<?php echo set_value('dob'); ?>" max="2015-01-01" min="1950-01-01"/> 
                                <span class="text-danger"><?php echo form_error('dob'); ?></span>
                            </div>

                            <div class="form-group">
                                <label for="gender">Giới tính </label>
                                <input type="radio" name="gender" value="1" checked > Nam
                                <input type="radio" name="gender" value="0"> Nữ
                            </div>

                            <div class="form-group">
                                <label for="email">Email</label>
                                <input class="form-control" name="email" placeholder="Email" type="email" value="<?php echo set_value('email'); ?>" />
                                <span class="text-danger"><?php echo form_error('email'); ?></span>
                            </div>

                            <div class="form-group">
                                <label for="phone">Số điện thoại</label>
                                <input class="form-control" name="phone" type="text" value="<?php echo set_value('phone'); ?>" />
                                <span class="text-danger"><?php echo form_error('phone'); ?></span>
                            </div>

                            <div class="form-group">
                                <label for="subject">Mật khẩu</label>
                                <input class="form-control" name="password" placeholder="Mật khẩu" type="password" />
                                <span class="text-danger"><?php echo form_error('password'); ?></span>
                            </div>

                            <div class="form-group">
                                <label for="subject">Xác nhận mật khẩu</label>
                                <input class="form-control" name="cpassword" placeholder="Đánh lại mật khẩu ở trên" type="password" />
                                <span class="text-danger"><?php echo form_error('cpassword'); ?></span>
                            </div>

                            <div class="form-group">
                                <label for="autho">Loại tài khoản </label>
                                <input type="radio" name="autho" value="1" checked> Thực khách
                                <input type="radio" name="autho" value="2" > Chủ nhà hàng


                            </div>

                            <div id="myAddress" style="display: none">
                                <div class="form-group" >
                                    <label for="address">Địa chỉ</label>
                                    <input class="form-control" name="address" type="text" value="<?php echo set_value('address'); ?>" />
                                    <span class="text-danger"><?php echo form_error('address'); ?></span>
                                </div>

                                <div class="form-group">
                                    <label for="province">Tỉnh thành</label>
                                    <select class="form-control" name="province" size="1">
                                        <?php
                                        foreach ($province as $key => $row) {
                                            echo '<option value="' . $row['provinceID'] . '">' . $row['typePro'] . ' ' . $row['namePro'] . '</option>';
                                        }
                                        ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="district">Quận huyện</label>
                                    <select class="form-control" name="district" size="1">
                                        <?php
                                        foreach ($district as $key => $row) {
                                            echo '<option value="' . $row['districtid'] . '">' . $row['typeDis'] . ' ' . $row['nameDis'] . '</option>';
                                        }
                                        ?>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label for="ward">Khu vực</label>
                                    <select class="form-control" name="ward" size="1">
                                        <?php
                                        foreach ($ward as $key => $row) {
                                            echo '<option value="' . $row['wardid'] . '">' . $row['typeWard'] . ' ' . $row['nameWard'] . '</option>';
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <button name="submit" type="submit" class="btn btn-default">Đăng ký</button>
                                <button name="cancel" type="reset" class="btn btn-default">Hủy bỏ</button>
                            </div>
<?php echo form_close(); ?>
                            <?php echo $this->session->flashdata('msg'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="<?php echo base_url(); ?>js/register.js"></script>
    </body>
</html>