<div class="container">
    <div class="row">

        <div class="topdisplay-item">
            <?php $this->load->view('site/home/index/item.phtml', $resMaxRankModel) ?>
        </div> 
        <div class="topdisplay-item">
            <?php $this->load->view('site/home/index/item.phtml', $resCountdownModel) ?>
        </div> 
<!--        hết hiển thị nhà hàng-->

        <div class="topdisplay-item">
            <?php $this->load->view('site/home/index/news.phtml', $newsModel) ?>
        </div>

    </div>
</div>