<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="alert alert-success" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">Thông báo:</span>
              <?php echo $error; ?> <a href="<?php echo base_url()?>home">Vể trang chủ</a>
            </div>
        </div>
    </div>
</div>