
<ul class="form-group">
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="categoryOfResID">Danh mục nhà hàng (*)</label>
        <select id="categoryOfResID" name="categoryOfResID"  data-placeholder="--Chọn loại nhà hàng--" multiple class = "chosen-select">
           <?php foreach($categories as $item){?>
             <option id="<?php echo $item->categoryOfResID; ?>" value="<?php echo $item->categoryOfResID; ?>" 
                <?php if(isset($categoryOfResID) && in_array($item->categoryOfResID, $categoryOfResID)){ echo 'selected="selected"';} else {echo '';} ?> >
             <?php echo $item->nameCOR; ?>
             </option>
          <?php } ?>
        </select>
        <input type="hidden" name="categoryOfResIDs" id="categoryOfResIDs" value="<?php echo isset($categoryOfResIDs) ? $categoryOfResIDs : ''; ?>">
    </li> 
    <li class="row">
        <input type="hidden" id="restaurantID" name="restaurantID" value="<?php echo isset($restaurantID) ? $restaurantID : '0'; ?>">
        <input type="hidden" id="userID" name="userID" value="<?php echo isset($userID) ? $userID : '0'; ?>">
        <label class="col-md-3 col-sm-3 col-xs-3" for="memName">Tên nhà hàng(*)</label>
        <input class="col-md-6 col-sm-9 col-xs-9" type="text" value="<?php echo isset($nameRe) ? $nameRe : ''; ?>" id="nameRe"  name="nameRe">
    </li>
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="userName">Điện thoại(*)</label>
        <input class="col-md-6 col-sm-9 col-xs-9" type="text" id="phoneRe"  name="phoneRe"  value="<?php echo isset($phoneRe) ? $phoneRe : ''; ?>">
    </li>
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="favouriteFood">Món ăn nổi bật(*)</label>
        <input class="col-md-6 col-sm-9 col-xs-9" type="text" id="favouriteFood"  name="favouriteFood"  value="<?php echo isset($favouriteFood) ? $favouriteFood : ''; ?>">
    </li>
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" class="col-md-3 col-sm-3 col-xs-3" for="spaceRes">Không gian nhà hàng(*)</label>
        <input class="col-md-6 col-sm-9 col-xs-9" type="text" id="spaceRes"  name="spaceRes"  value="<?php echo isset($spaceRes) ? $spaceRes : ''; ?>">
    </li>
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="carParkingRes">Chỗ đỗ xe</label>
        <select class="col-md-6 col-sm-9 col-xs-9" id="carParkingRes" name="carParkingRes" style="with: 25%">
            <option id="0" value="0" <?php if(isset($carParkingRes) && $carParkingRes == 0){ echo 'selected="selected"';} else {echo '';} ?> >Không</option>
            <option id="1" value="1" <?php if(isset($carParkingRes) && $carParkingRes == 1){ echo 'selected="selected"';} else {echo '';} ?> >Có</option>
        </select>
    </li>
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="otherPoints">Điểm đặc trưng khác</label>
        <input class="col-md-6 col-sm-9 col-xs-9" type="text" id="otherPoints"  name="otherPoints"  value="<?php echo isset($otherPoints) ? $otherPoints : ''; ?>">
    </li>
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="openTimeRe">Giờ mở cửa</label>
        <div class="col-md-3 col-sm-6 col-xs-6 R-time">
            <input placeholder="Mở cửa" class="textbox-n" type="text" onfocus="(this.type='time')" onblur="(this.type='text')" id="openTimeRe" name="openTimeRe" value="<?php echo isset($openTimeRe) ? $openTimeRe : ''; ?>">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
        </div>
	</li>
	<li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="closeTimeRe">Giờ đóng cửa</label>
        <div class="col-md-3 col-sm-6 col-xs-6 R-time">
            <input placeholder="Mở cửa" class="textbox-n" type="text" onfocus="(this.type='time')" onblur="(this.type='text')" id="closeTimeRe" name="closeTimeRe" value="<?php echo isset($closeTimeRe) ? $closeTimeRe : ''; ?>">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
        </div>
    </li>


    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3" for="rateRe">Đánh giá nhà hàng</label>
        <input class="col-md-3 col-sm-6 col-xs-6" readonly="readonly" type="text" id="rateRe"  name="rateRe"  value="<?php echo isset($rateRe) ? $rateRe : ''; ?>">
    </li>
    <li class="row">
        <label class="col-md-3 col-sm-3 col-xs-3">Trạng thái</label>
        <span class="edit-checkbox">
            <?php if(isset($statusRes) && $statusRes) echo '<font color="green">Hoạt động</font>'; else echo '<font color="red">Chưa kích hoạt</font>';?>
        </span>
        <span style="display: none" class="edit-checkbox">
            <input type="checkbox" name="statusRes" id="statusRes" <?php echo (isset($statusRes) && $statusRes) ? 'checked': ''; ?>> Trạng thái
        </span>
</ul>
<script type="">
    $('.datepicker').datetimepicker({locale: 'vi'});
    $('.time').datetimepicker({locale: 'vi',format: 'HH:mm'});
    $(".chosen-select").chosen().change(function(evt){
        var arr = $(".chosen-select").chosen().val();
        $('#categoryOfResIDs').val(arr.join());
    });
    $(document).ready(function(){
        var ok = '<?php echo isset($ok) ? $ok : ''; ?>';
        if (ok == '1')
        {
            setTimeout(function(){
                location.href = '<?php echo base_url().'user_profile/restaurant_edit'; ?>';    
            }, 2000)                                                                       
        }
    })
</script>