<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
        <h2>Danh sách nhà hàng</h2>
  </div>
  <div class="panel-body">
    
  <!-- Table -->
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Loại hình ẩm thực</th>
            <th>Tên nhà hàng</th>
            <th class="col-lg-1 text-center">Điện thoại</th> 
            <th>Địa chỉ</th>
            <th class="col-lg-2 text-center">Trạng thái</th>
            <th class="col-lg-2"></th>
        </tr>
    </thead>
    <tbody>
        <?php if (isset($result)){ ?>
        <?php foreach ($result as $user) {?>
        <tr>
            <td><?php echo $user->restaurantID; ?></td>
            <td><?php echo $user->categoryName; ?></td>
            <td><?php echo $user->nameRe; ?></td>
            <td><?php echo $user->phoneRe; ?></td>
            <td><?php echo $user->address; ?></td>   
            <td class="text-center"><?php echo $user->statusRes ? 'Hoạt động' : 'Chưa kích hoạt'; ?></td>
            <td class="text-center">
            <a class="btn btn-info" href="<?php echo base_url()?>admin/edit_restaurant/<?php echo $user->restaurantID; ?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Xem</a>
            <a class="btn btn-danger" onclick="return resModule.delete('<?php echo $user->nameRe; ?>');" href="<?php echo base_url()?>admin/delete_restaurant/<?php echo $user->restaurantID; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i> Xóa</a>
            </td>
        </tr>
        <?php } ?>
        <?php } ?>
    </tbody>
    <tfoot>
        <tr>
        <td colspan="7">                      
        <?php echo $pagination; ?>
        </td>
        </tr>
    </tfoot>
  </table>
  </div>
      
</div>
<script type="text/javascript">
    window.resModule = window.resModule || {};
    
    resModule.delete = resModule.delete || function(name){
        if (confirm('Xóa nhà hàng ' + name + '?'))
            return true;
        return false;
    }
</script>