<form method="POST" action="" id="frmres">
    <div class="panel panel-default">
      <!-- Default panel contents -->
          <div class="panel-heading">
              <h2><?php echo $title;?></h2>
          </div>

          <div class="panel-body">
              <a style="margin-bottom: 15px" class="btn btn-default" href="<?php echo base_url()?>admin/restaurant" role="button"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Quay về</a>

              <?php if($error!='' && $error!=null){?>
                  <div class="bg-danger"><?php echo $error; ?></div>
              <?php }else if($success!='' && $success!=null){?>
                  <div class="bg-success"><?php echo $success; ?></div>
              <?php }?>

              <ul class="nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#_res_info">Thông tin chung</a></li>
                  <li><a data-toggle="tab" href="#_res_add">Địa chỉ</a></li>
                  <li><a data-toggle="tab" href="#_res_desc">Mô tả</a></li>
                  <li><a data-toggle="tab" href="#_res_food">Món ăn</a></li>
              </ul>

              <div class="tab-content">
                  <div id="_res_info" class="tab-pane fade in active">
                      <?php $this->load->view('admin/restaurant/info.phtml'); ?>
                  </div>
                  <div id="_res_add" class="tab-pane fade in">
                      <?php $this->load->view('admin/restaurant/address.phtml'); ?>
                  </div>
                  <div id="_res_desc" class="tab-pane fade in">
                      <div class="col-lg-12 form-group" style="padding-top: 15px">
                          <textarea readonly="readonly" id="descriptionRes" name="descriptionRes">
                              <?php echo isset($descriptionRes) ? $descriptionRes : ''; ?>
                          </textarea>
                      </div>
                  </div>
                  <div id="_res_food" class="tab-pane fade in">
                      <?php
                      if (isset($restaurantID) && $restaurantID > 0)
                          $this->load->view('admin/restaurant/foods.phtml');
                      ?>
                  </div>
              </div>
              <button name="submit" id="submit" class="btn btn-primary" value="save"><i class="fa fa-floppy-o" aria-hidden="true"></i> Lưu</button>
          </div>
    </div>
</form>

<script type=""> 
    CKFinder.setupCKEditor(null, '/resource/ckfinder/' );
    CKEDITOR.replace("descriptionRes");
    $(document).ready(function(){
        var ok = '<?php echo isset($ok) ? $ok : ''; ?>';
        if (ok == '1')
        {
            setTimeout(function(){
                location.href = '<?php echo base_url().'admin/restaurant'; ?>';
            }, 2000)
        }
    })
</script>