
<div style="display: table; padding-top: 15px">
    <div class="col-lg-12 form-group">
        <label for="categoryOfResID">Danh mục nhà hàng</label> 
        <select disabled="true" id="categoryOfResID" name="categoryOfResID"  data-placeholder="--Chọn loại nhà hàng--" multiple class="chosen-select">
           <?php foreach($categories as $item){?>
             <option id="<?php echo $item->categoryOfResID; ?>" value="<?php echo $item->categoryOfResID; ?>" 
                <?php if(isset($categoryOfResID) && in_array($item->categoryOfResID, $categoryOfResID)){ echo 'selected="selected"';} else {echo '';} ?> >
             <?php echo $item->nameCOR; ?>
             </option>
          <?php } ?>
        </select>
    	<input type="hidden" name="categoryOfResIDs" id="categoryOfResIDs" value="<?php echo isset($categoryOfResIDs) ? $categoryOfResIDs : ''; ?>">
    </div>

    <div class="col-lg-12 form-group">
        <input type="hidden" id="restaurantID" name="restaurantID" value="<?php echo isset($restaurantID) ? $restaurantID : '0'; ?>">
        <input type="hidden" id="userID" name="userID" value="<?php echo isset($userID) ? $userID : '0'; ?>">
        <label for="memName">Tên nhà hàng</label>
        <input readonly="readonly" type="text" class="form-control" value="<?php echo isset($nameRe) ? $nameRe : ''; ?>" id="nameRe"  name="nameRe"> 
    </div>

    <div class="col-lg-6 form-group">
        <label for="userName">Điện thoại</label>
        <input readonly="readonly" type="text" class="form-control" id="phoneRe"  name="phoneRe"  value="<?php echo isset($phoneRe) ? $phoneRe : ''; ?>"> 
    </div>

    <div class="col-lg-6 form-group">
        <label for="userID">Người dùng</label> 
        <input disabled="disabled" id="userID" name="userID" class="form-control" value="<?php foreach($users as $item){if(isset($userID) && $userID == $item->userID.''){echo $item->userName;}} ?>">
    </div>

    <div class="col-lg-12 form-group">
        <label for="favouriteFood">Món ăn đặc sắc</label>
        <input readonly="readonly" type="text" class="form-control" id="favouriteFood"  name="favouriteFood"  value="<?php echo isset($favouriteFood) ? $favouriteFood : ''; ?>">
    </div>     
    <div class="col-lg-6 form-group">
        <label for="spaceRes">Không gian nhà hàng</label>
        <input readonly="readonly" type="text" class="form-control" id="spaceRes"  name="spaceRes"  value="<?php echo isset($spaceRes) ? $spaceRes : ''; ?>"> 
    </div>       
    <div class="col-lg-6 form-group">
        <label for="carParkingRes">Chỗ đỗ xe</label>
        <input readonly="readonly" type="text" class="form-control" id="carParkingRes"  name="carParkingRes"  value="<?php echo isset($carParkingRes) && $carParkingRes == 1 ? 'Có' : 'Không'; ?>"> 
    </div>  
    <div class="col-lg-12 form-group">
        <label for="otherPoints">Điểm đặc trưng khác</label>
        <input readonly="readonly" type="text" class="form-control" id="otherPoints"  name="otherPoints"  value="<?php echo isset($otherPoints) ? $otherPoints : ''; ?>"> 
    </div>    
    <div class="col-lg-4 form-group">
        <label for="openTimeRe">Giờ mở của</label>
        <div class=' input-group date time'>
            <input readonly="readonly" type="text" class="form-control" id="openTimeRe"  name="openTimeRe"  value="<?php echo isset($openTimeRe) ? $openTimeRe : ''; ?>"> 
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>
    <div class="col-lg-4 form-group">
        <label for="closeTimeRe">Giờ đóng cửa</label>
        <div class=' input-group date time'>
            <input readonly="readonly" type="text" class="form-control" id="closeTimeRe"  name="closeTimeRe"  value="<?php echo isset($closeTimeRe) ? $closeTimeRe : ''; ?>"> 
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>      
    <div class="col-lg-4 form-group">
        <label for="rateRe">Đánh giá nhà hàng</label>
        <select id="rateRe" name="rateRe" class="form-control">
            <option id="0" value="0" <?php if(isset($rateRe) && $rateRe == 0){ echo 'selected="selected"';} else {echo '';} ?> >0 *</option>
            <option id="1" value="1" <?php if(isset($rateRe) && $rateRe == 1){ echo 'selected="selected"';} else {echo '';} ?> >1 *</option>
            <option id="2" value="2" <?php if(isset($rateRe) && $rateRe == 2){ echo 'selected="selected"'; } else {echo '';} ?>>2 *</option>
            <option id="3" value="3" <?php if(isset($rateRe) && $rateRe == 3){ echo 'selected="selected"'; } else {echo '';} ?>>3 *</option>
            <option id="4" value="4" <?php if(isset($rateRe) && $rateRe == 4){ echo 'selected="selected"'; } else {echo '';} ?>>4 *</option>
            <option id="5" value="5" <?php if(isset($rateRe) && $rateRe == 5){ echo 'selected="selected"'; } else {echo '';} ?>>5 *</option>
        </select>
    </div>  
    <div class="col-lg-4 form-group">
        <div class="checkbox">
            <label>
              <input type="checkbox" name="statusRes" id="statusRes" <?php echo (isset($statusRes) && $statusRes) ? 'checked': ''; ?>>Kích hoạt
            </label>
        </div>
    </div>
    <div  style="display: none"  class="col-lg-4">
          <div class="checkbox">
            <label>
              <input type="checkbox" name="isDepositBo" id="isDepositBo" <?php echo (isset($isDepositBo) && $isDepositBo) ? 'checked': ''; ?>>isDepositBo
            </label>
          </div>
    </div>
    <div style="display: none"  class="col-lg-4 form-group">
          <div class="checkbox">
            <label>
              <input type="checkbox" name="isDeactivate" id="isDeactivate" <?php echo (isset($isDeactivate) && $isDeactivate) ? 'checked': ''; ?>>Dừng hoạt động
            </label>
          </div>
    </div>
    <div style="display: none"  class="col-lg-4 form-group">
          <div class="minPrice">
            <label for="minPrice">Giá tiền (thấp - cao: vnđ)</label>
            <input style="width: 24.3%" type="number" id="minPrice"  name="minPrice"  value="<?php echo isset($minPrice) ? $minPrice : ''; ?>"> -
            <input style="width: 24.3%" type="number" id="maxPrice"  name="maxPrice"  value="<?php echo isset($maxPrice) ? $maxPrice : ''; ?>">
          </div>
    </div>
    <div style="display: none"  class="col-lg-4 form-group">
          <div class="minPrice">
            <label for="discount">Giảm giá (%)</label>
            <input type="number" id="discount"  name="discount"  value="<?php echo isset($discount) ? $discount : ''; ?>">
          </div>
    </div>

</div>  
<script type="">
    $('.datepicker').datetimepicker({locale: 'vi'});
    $('.time').datetimepicker({locale: 'vi',format: 'HH:mm'});
	$(".chosen-select").chosen().change(function(evt){
        var arr = $(".chosen-select").chosen().val();
        $('#categoryOfResIDs').val(arr.join());
    });    
    $(document).ready(function(){
        var ok = '<?php echo isset($ok) ? $ok : ''; ?>';
        if (ok == '1')
        {
            setTimeout(function(){
                location.href = '<?php echo base_url().'admin/restaurant'; ?>';    
            }, 2000)                                                                       
        }
    })
</script>