<h1>Đổi mật khẩu</h1>  
<div class="bg-danger"><?php echo $error; ?></div>
<form class="edit-user" method="POST">
    <ul>
        <li>
            <label>Mật khẩu cũ:</label> 
            <input type="password" value="<?php echo isset($passwordOld) ? $passwordOld : ''; ?>" id="passwordOld"  name="passwordOld" placeholder="Mật khẩu cũ"> 
        </li>
        <li>
            <label>Mật khẩu mới:</label>              
            <input type="password" id="password"  name="password"  value="<?php echo isset($password) ? $password : ''; ?>" placeholder="Mật khẩu mới"> 
        </li>  
        <li>
            <label>Gõ lại:</label>              
            <input type="password" id="passwordRe"  name="passwordRe"  value="" placeholder="Mật khẩu mới"> 
        </li>  
        <li>
            <label></label>
            <input type="submit" name="submit" value="Cập nhật">
        </li>
    </ul>
</form>
<script type="">

</script>  