<link rel="stylesheet" href="<?php echo base_url() ?>css/user.css">

<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">

            <?php $this->load->view('site/user/user/profile_image.phtml'); ?>

            <ul class="profile-sidebar">
                <li><a href="<?php echo base_url(); ?>user"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li class="active"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li><a href=""><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li><a href=""><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>

                <li><a href="<?php echo base_url(); ?>booking/viewBooking"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/sign_out"><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Quản lý Banner</h1>

            <ul style="margin: 40px 0">
                <?php
                for ($i = 0; $i < 6; $i++) {
                    if ($i < count($banner)) {
                        echo form_open_multipart('image/changeBanner');
                        ?>
                        <li class="upload-banner">
                            <img id="banner<?php echo $i; ?>" src="<?php echo base_url($banner[$i]->addressImage) ?>" height="600px" width="800px" alt="banner" />

                            <input type="hidden" name="preImgID" value="<?php echo $banner[$i]->imageID ?>" >
                            <input type="hidden" name="preImgAddr" value="<?php echo $banner[$i]->addressImage ?>" >

                            <input type="text" name="descriptionImage" placeholder="write description" value="<?php echo $banner[$i]->descriptionImage ?>" style="border-color: yellow;"><br />
                            <label class = "select-file-btn">
                                <input type="file" name="filename" onchange="readURL<?php echo $i; ?>(this);" />  
                                <a>
                                    <i class="fa fa-plus" aria-hidden="true"></i>Add
                                </a>
                            </label>
                            <span class="text-danger"><?php
                                if (isset($error)) {
                                    echo $error;
                                }
                                ?>
                            </span>
                        </li>
                        <li class="upload-banner">
                            <input type="submit" value="Cập nhật">
                        </li>
                        <?php
                        echo form_close();
                        if (isset($success_msg)) {
                            echo $success_msg;
                        }
                    } else {
                        echo form_open_multipart('image/changeBanner');
                        ?>
                        <li class="upload-banner">
                            <!--                        <a>
                                                        <i class="fa fa-plus" aria-hidden="true"></i>Add
                                                    </a>-->
                                                    <!--<input class="" type="text" placeholder="Viết tiêu đề...">-->
                            <input type="text" name="descriptionImage" placeholder="write description" style="border-color: yellow; border-width: 3px;"><br />
                            <input type="file" name="filename" onchange="readURL<?php echo $i; ?>(this);" />
                            <img id="banner<?php echo $i; ?>" src="<?php echo base_url('images/restOwner/banner/default_banner.png'); ?>" alt="banner" />
                            <span class="text-danger"><?php
                                if (isset($error)) {
                                    echo $error;
                                }
                                ?>
                            </span>
                        </li>
                        <li class="upload-banner">
                            <input type="submit" value="Cập nhật">
                        </li>
                        <?php
                        echo form_close();
                        if (isset($success_msg)) {
                            echo $success_msg;
                        }
                    }
                }
                ?>
            </ul>
        </div>
    </div>
</div>

<!--preview images-->
<script>

    function readURL0(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#banner0')
                        .attr('src', e.target.result)
                        .width(800)
                        .height(600);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function readURL1(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#banner1')
                        .attr('src', e.target.result)
                        .width(800)
                        .height(600);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function readURL2(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#banner2')
                        .attr('src', e.target.result)
                        .width(800)
                        .height(600);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function readURL3(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#banner3')
                        .attr('src', e.target.result)
                        .width(800)
                        .height(600);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function readURL4(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#banner4')
                        .attr('src', e.target.result)
                        .width(800)
                        .height(600);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function readURL5(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#banner5')
                        .attr('src', e.target.result)
                        .width(800)
                        .height(600);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

}
