<link rel="stylesheet" href="<?php echo base_url() ?>css/user.css">

<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            <table class="profile-stt">
                <tr>
                    <td><img src="http://cdn.pasgo.vn/images/Profile/no_avatar.png"></td>
                    <td>
                        <p>ID ĂnGì: <strong><?php echo $this->session->userdata("ID"); ?></strong></p>
                        <p>ĐT: <strong><?php echo $this->session->userdata("phone"); ?></strong></p>
                    </td>
                </tr>

                <tr>
                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
                    <td></td>
                </tr>
            </table>
            <ul class="profile-sidebar">
                <li><a href="<?php echo base_url(); ?>user"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li class="active"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li><a href=""><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li><a href=""><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>
                <li><a><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
                <li><a><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Quản lý Banner</h1>

            <ul style="margin: 40px 0">
                <?php
                $tempRestID = 2;
                
                if (isset($success)) {
                        echo $success;
                        $error = null;
                    } else if (isset($error)) {
                        echo $error;
                        $success = null;
                    } else {
                        $success = null;
                        $error = null;
                    }
                for ($i = 0; $i < 6; $i++) {
                    ?>
                    <form action="<?php echo base_url('upload/addBanner/' . $tempRestID); ?>" method="post" enctype="multipart/form-data">
                        <!--                        <li class="upload-banner">
                                                    <a>
                                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                                        Thêm ảnh
                                                    </a>
                                                    <input class="" type="text" placeholder="Viết tiêu đề...">
                                                    <input type="text" placeholder="Viết mô tả...">
                                                </li>-->

                        <input type="file" name="userfile" id="banner<?php echo $i; ?>"/> 
                        <br />
                        <img id="img<?php echo $i; ?>" src="<?php echo base_url(); ?>uploads/image/10168260_1762021884033784_894591750_n.jpg" alt="banner" />
                        <li class="upload-banner">
                            <input type="submit" value="Cập nhật">
                        </li>
                        <br /><br /> 
                        <hr />
                    </form>
                    <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>

<!--Java script for preview image-->
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#img0").attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#banner0").change(function () {
        readURL(this);
    });

    function readURL1(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#img1").attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#banner1").change(function () {
        readURL1(this);
    });
    function readURL2(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#img2").attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#banner2").change(function () {
        readURL2(this);
    });
    function readURL3(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#img3").attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#banner3").change(function () {
        readURL3(this);
    });
    function readURL4(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#img4").attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#banner4").change(function () {
        readURL4(this);
    });
    function readURL5(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $("#img5").attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("#banner5").change(function () {
        readURL5(this);
    });

</script>