<link rel="stylesheet" href="<?php echo base_url()?>css/user.css">
<script src="../resource/ckeditor/ckeditor.js"></script>


<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            <table class="profile-stt">
                <tr>
                    <td><img src="http://cdn.pasgo.vn/images/Profile/no_avatar.png"></td>
                    <td>
                        <p>ID ĂnGì: <strong><?php echo $this->session->userdata("ID"); ?></strong></p>
                        <p>ĐT: <strong><?php echo $this->session->userdata("phone"); ?></strong></p>
                    </td>
                </tr>

                <tr>
                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
                    <td></td>
                </tr>
            </table>
            <ul class="profile-sidebar">
                <li><a href="<?php echo base_url(); ?>user"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                <li  class="active"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_price"><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li><a href="<?php echo base_url(); ?>booking/manageReservation"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/change_password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</li></li>
                <li><a href="<?php echo base_url(); ?>booking/viewBooking"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/sign_out"><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Thông tin nhà hàng</h1>
            <form class="edit-user">
                <ul>
                    <li>
                        <label>Loại hình ẩm thực:</label> 
                        <select class="" name="category" size="1">
                            <?php 
                                foreach ($categoriesData as $key => $row)
                                {
                                   echo '<option value="' . $row['categoryOfResID'] . '">' .$row['nameCOR']. '</option>';
                                }
                            ?>
                        </select>
                    </li>

                    <li>
                        <label>Món đặc sắc:</label> <input type="text" value="" name = "favouriteFood">
                    </li>
                    <li>
                        <label>Giá trung bình/người (VNĐ):</label>  <input type="text" value="" name = "minPrice">
                        <input type="text" value="" name = "maxPrice">
 
                    </li>
                    <li>
                        <label>Không gian:</label> <input type="text" value="" name="spaceRes">
                    </li>
                    <li>
                        <label>Chỗ để ô tô:</label> <input type="checkbox" name="carParkingRes" value="1"><br>
                    </li>
                    <li>
                        <label>giờ đóng/mở cửa:</label> <input type="time" value="" name="closeTimeRe">
                         đến &nbsp&nbsp<input type="time" value="" name="openTimeRe">
                    </li>

                    <li>
                        <label>Điểm đặc trưng khác:</label> <input type="text" value="">
                    </li>
                    <li>
                        <label>Nội dung:</label>
                        <textarea class="ckeditor" name="editor"></textarea>
                    </li>
                    <li>
                        <label></label>
                        <input type="submit" value="Cập nhật">
                    </li>
                </ul>
            </form>
        </div>
    </div>
</div>