<link rel="stylesheet" href="<?php echo base_url() ?>css/user.css">
<script src="../resource/ckeditor/ckeditor.js"></script>


<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">

            <?php $this->load->view('site/user/profile/profile_image.phtml'); ?>

            <ul class="profile-sidebar">
                <li><a href="<?php echo base_url(); ?>user"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                <li  class="active"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_menu"><i class="fa fa-usd" aria-hidden="true"></i> Bảng Menu</a></li>
                <li><a href="<?php echo base_url(); ?>booking/manageReservation"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/change_password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</li></li>
                <li><a href="<?php echo base_url(); ?>booking/viewBooking"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/sign_out"><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Thông tin nhà hàng</h1>
            <?php
            echo $this->session->flashdata('msgResInfo');
            if (count($resData) < 1) {
                ?>
                <form class="edit-user" action="<?php echo base_url() ?>restaurant/addNewRes">
                    <h3>Chưa tạo nhà hàng</h3>
                    <input type="submit" value="Tao nhà hàng">
                </form>
                <?php
            } else {
                ?>

                <?php echo form_open_multipart('image/changeAvatar/restImgFile'); ?>
                <img id="restImage" src="<?php echo base_url($restImageAddr); ?>" height="250" width="300" alt="restaurant image" >
                <label class = "select-file-btn">
                    <input type="file" name="restImgFile" onchange="readRestImageUrl(this);" />
                    Tai anh profile nhà hàng
                </label>
                <input type="submit" value="Save" id="btnRestProfile" disabled />
                <span class="text-danger">
                    <?php
                    if (isset($error)) {
                        echo $error;
                    }
                    ?>
                </span>
                <?php
                echo form_close();
                if (isset($success_msg)) {
                    echo $success_msg;
                }
                ?>

                <form class="edit-user" method="POST">
                    <ul>
                        <li>
                            <label>Tên nhà hàng:</label> <input type="text" value="<?php echo $resData[0]['nameRe']; ?>" name="nameRe" >
                            <input type="hidden" value="<?php echo base_url($restImageAddr); ?>" />
                            <span class="text-danger"><?php echo form_error('nameRe'); ?></span>
                        </li>
                        <li>
                            <label>Loại hình ẩm thực:</label> 
                            <?php
                            if (count($resCateData) < 1) {
                                foreach ($categoriesData as $key => $row) {
                                    echo '<input type="checkbox" name="categoryOfResID[]" value="' . $row['categoryOfResID'] . '">&nbsp' . $row['nameCOR'] . '&nbsp &nbsp &nbsp &nbsp';
                                }
                            } else {
                                foreach ($categoriesData as $key => $row) {
                                    if (in_array($row['categoryOfResID'], $resCateData)) {
                                        echo '<input type="checkbox" name="categoryOfResID[]" value="' . $row['categoryOfResID'] . '" checked >&nbsp' . $row['nameCOR'] . '&nbsp &nbsp &nbsp &nbsp';
                                    } else {
                                        echo '<input type="checkbox" name="categoryOfResID[]" value="' . $row['categoryOfResID'] . '" >&nbsp' . $row['nameCOR'] . '&nbsp &nbsp &nbsp &nbsp';
                                    }
                                }
                            }
                            ?>
                        </li>

                        <li>
                            <label>Campaign:</label> <input type="text" value="<?php echo $resData[0]['campaign']; ?>" name = "campaign">
                            <span class="text-danger"><?php echo form_error('campaign'); ?></span>
                        </li>

                        <li>
                            <label>Món đặc sắc:</label> <input type="text" value="<?php echo $resData[0]['favouriteFood']; ?>" name = "favouriteFood">
                            <span class="text-danger"><?php echo form_error('favouriteFood'); ?></span>
                        </li>

                        <li>
                            <label>Số điện thoại :</label> <input type="text" value="<?php echo $resData[0]['phoneRe']; ?>" name = "phoneRe">
                            <span class="text-danger"><?php echo form_error('phoneRe'); ?></span>
                        </li>
                        <li>
                            <label>Giá trung bình/người (vnđ):</label>
                            <div class="inline-double-text">
                                <div class="row">
                                    <div class="col-md-6">
                                        <input placeholder="Từ..." class="textbox-n" type="number" value="<?php echo $resData[0]['minPrice']; ?>" name="minPrice" onfocus="(this.type = 'number')" onblur="(this.type = 'text')">
                                    </div>
                                    <div class="col-md-6">
                                        <input placeholder="Đến..." class="textbox-n" type="number" value="<?php echo $resData[0]['maxPrice']; ?>" name="maxPrice" onfocus="(this.type = 'number')" onblur="(this.type = 'text')">
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <label>Không gian:</label> <input type="text" value="<?php echo $resData[0]['spaceRes']; ?>" name="spaceRes">
                            <span class="text-danger"><?php echo form_error('spaceRes'); ?></span>
                        </li>
                        <li>
                            <label>Chỗ để ô tô:</label>
                            <?php
                            if ($resData[0]['carParkingRes'] == 1) {
                                ?>
                                <input type="radio" name="carParkingRes" value="0"> Không
                                <input style="margin-left: 100px;" type="radio" name="carParkingRes" value="1" checked> Có


                                <?php
                            } else {
                                ?>
                                <input type="radio" name="carParkingRes" value="0" checked> Không
                                <input style="margin-left: 100px;" type="radio" name="carParkingRes" value="1" > Có

                            <?php } ?>

                                                                        <!--                         <input type="radio" name="gender" value="yes" checked> Có
                                                                                                <input style="margin-left: 100px;" type="radio" name="no" value="female"> Không -->
                        </li>
                        <li>
                            <label>Hoạt động</label>
                            <div class="inline-double-text">
                                <div class="row">
                                    <div class="col-md-6">
                                        <input placeholder="Mở cửa" class="textbox-n" type="text" name="openTimeRe" value="<?php echo $resData[0]['openTimeRe']; ?>" onfocus="(this.type = 'time')" onblur="(this.type = 'text')">
                                    </div>
                                    <div class="col-md-6">
                                        <input placeholder="Đóng cửa" class="textbox-n" type="text" name="closeTimeRe" value="<?php echo $resData[0]['closeTimeRe']; ?>" onfocus="(this.type = 'time')" onblur="(this.type = 'text')">
                                    </div>
                                </div>
                            </div>

                        </li>       
                        <li>
                            <label>Mức giảm giá (%):</label> 
                            <input class="textbox-n" type="number" name="discount" value="<?php echo $resData[0]['discount']; ?>" onfocus="(this.type = 'number')" onblur="(this.type = 'text')">
                        <li>
                            <label>Điểm đặc trưng khác:</label> <input type="text" name="otherPoints" value="<?php echo $resData[0]['otherPoints']; ?>">
                        </li>

                        <li>
                            <label>Địa chỉ:</label> <input type="text" name="address" value="<?php
                            echo $addressData[0]['address'];
                            ?>">
                        </li>

                        <li>
                            <label>Tỉnh thành:</label> 
                            <select name="province" size="1">
                                <?php
                                foreach ($province as $key => $row) {
                                    if ($addressData[0]['provinceID'] == $row['provinceID']) {
                                        echo '<option value="' . $row['provinceID'] . '" selected >' . $row['typePro'] . ' ' . $row['namePro'] . '</option>';
                                    } else {
                                        echo '<option value="' . $row['provinceID'] . '">' . $row['typePro'] . ' ' . $row['namePro'] . '</option>';
                                    }
                                }
                                ?>
                            </select>

                        </li>
                        <li>
                            <label>Quận huyện:</label> 
                            <select name="district" size="1">
                                <?php
                                foreach ($district as $key => $row) {
                                    if ($addressData[0]['districtid'] == $row['districtid']) {
                                        echo '<option value="' . $row['districtid'] . '" selected >' . $row['typeDis'] . ' ' . $row['nameDis'] . '</option>';
                                    } else {
                                        echo '<option value="' . $row['districtid'] . '">' . $row['typeDis'] . ' ' . $row['nameDis'] . '</option>';
                                    }
                                }
                                ?>
                            </select>
                        </li>
                        <li>
                            <label>Khu vực:</label>
                            <select name="ward" size="1">
                                <?php
                                foreach ($ward as $key => $row) {
                                    if ($addressData[0]['wardid'] == $row['wardid']) {
                                        echo '<option value="' . $row['wardid'] . '" selected >' . $row['typeWard'] . ' ' . $row['nameWard'] . '</option>';
                                    }
                                    echo '<option value="' . $row['wardid'] . '">' . $row['typeWard'] . ' ' . $row['nameWard'] . '</option>';
                                }
                                ?>
                            </select>                        
                        </li>             


                        <li>
                            <label>Nội dung:</label>
                            <textarea class="ckeditor" name="editor"><?php echo $resData[0]['descriptionRes']; ?></textarea>
                        </li>
                        <li>
                            <label></label>
                            <input type="submit" value="Cập nhật">
                        </li>
                    </ul>
                </form>
            <?php } ?>
        </div>
    </div>
</div>

<script>
    function readRestImageUrl(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#restImage')
                        .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
            // enable submit button
            $("#btnRestProfile").removeAttr('disabled');
        }
    }
</script>