<link rel="stylesheet" href="<?php echo base_url() ?>css/user.css">
<script src="../resource/ckeditor/ckeditor.js"></script>


<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">

            <?php $this->load->view('site/user/profile/profile_image.phtml'); ?>

            <ul class="profile-sidebar">
                <li><a href="<?php echo base_url(); ?>user"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li class="active"><i class="fa fa-usd" aria-hidden="true"></i> Bảng Menu</li>
                <li><a href="<?php echo base_url(); ?>booking/manageReservation"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/change_password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>
                <li><a href="<?php echo base_url(); ?>booking/viewBooking"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
                <li><a href="<?php echo base_url(); ?>user/sign_out"><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <h1>Bảng giá</h1>
            <form class="edit-user">
                <ul>
                    <li>
                        <label>Cập nhật bảng giá:</label>
                        <textarea class="ckeditor" name="editor"></textarea>
                    </li>
                    <li>
                        <label></label>
                        <input type="submit" value="Cập nhật">
                    </li>
                </ul>
            </form>
        </div>
    </div>
</div>