<div class="container">
    <div class="row">
        <div class="col-md-4 footer-col">
            <p>Giải pháp PASGO giúp người dùng tìm kiếm Điểm đến gần nhất và đặt chỗ trực tuyến một cách nhanh chóng, tiện lợi.
                Ứng dụng đặt chỗ thông minh, đặt bàn online - PASGO đi đầu tại Việt Nam kết nối người dùng và điểm đến!</p>
        </div>

        <div class="col-md-3 footer-col">
            <ul>
                <li><a href="">CHÚNG TÔI</a> </li>
                <li><a href="">Quy chế hoạt động</a> </li>
                <li><a href="">Chính sách bảo mật</a> </li>
                <li><a href="">Cơ chế giải quyết</a> </li>
                <li><a href="">Đối tác</a> </li>
            </ul>
        </div>

        <div class="col-md-2 footer-col">
            <ul>
                <li><a>THAM GIA VỚI CHÚNG TÔI</a></li>
                <li>
                    <a class="social-logo" href="facebook.com">
                        <img src="http://cdn.pasgo.vn/images/Tintucs/facebook-PASGO.png">
                    </a>
                    <a class="social-logo" href="facebook.com">
                        <img src="http://cdn.pasgo.vn/images/Tintucs/Google-PASGO.png">
                    </a>
                    <a class="social-logo" href="facebook.com">
                        <img src="http://cdn.pasgo.vn/images/Tintucs/youtube-PASGO.png">
                    </a>
                </li>

            </ul>
        </div>
    </div>
</div>

<div id="fb-root"></div>