<link rel="stylesheet" href="<?php echo base_url()?>css/viewRestaurant.css">

<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="restaurant-home">
            <div class="col-md-12" style="margin-bottom: 20px">
                <h2 class="restaurant-name">Ao quán</h2>
            </div>

            <div class="col-md-3" style="float: right; position: relative">
                <div class="restaurant-rate shadow-outside">
                    <span style="font-size: 2em">
                        <i class="glyphicon glyphicon-star filled"></i>
                        <i class="glyphicon glyphicon-star filled"></i>
                        <i class="glyphicon glyphicon-star filled"></i>
                        <i class="glyphicon glyphicon-star filled"></i>
                        <i class="glyphicon glyphicon-star"></i>
                    </span>

                    <p>24 đánh giá</p>
                    <p>18 Ngõ 19 Đông Tác, Quận Đống Đa</p>
                </div>

                <div class="stick-point"></div>

                <?php $this->load->view('site/booking/index.phtml') ?>


            </div>

            <div class="col-md-9">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#info">Thông tin</a></li>
                    <li><a data-toggle="tab" href="#price">Bảng giá</a></li>
                </ul>

                <div class="tab-content">
                    <div id="info" class="tab-pane fade in active">


                        <div id="myCarousel-restaurant" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#myCarousel-restaurant" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel-restaurant" data-slide-to="1"></li>
                                <li data-target="#myCarousel-restaurant" data-slide-to="2"></li>
                                <li data-target="#myCarousel-restaurant" data-slide-to="3"></li>
                                <li data-target="#myCarousel-restaurant" data-slide-to="4"></li>
                                <li data-target="#myCarousel-restaurant" data-slide-to="5"></li>
                                <li data-target="#myCarousel-restaurant" data-slide-to="6"></li>
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="http://cdn.pasgo.vn/anh-chi-tiet/quan-an-ngon-18-phan-boi-chau-22-4889.jpg">
                                </div>

                                <div class="item">
                                    <img src="http://cdn.pasgo.vn/anh-chi-tiet/quan-an-ngon-18-phan-boi-chau-21-4890.JPG">
                                </div>

                                <div class="item">
                                    <img src="http://cdn.pasgo.vn/anh-chi-tiet/quan-an-ngon-18-phan-boi-chau-14-4891.JPG">
                                </div>

                                <div class="item">
                                    <img src="http://cdn.pasgo.vn/anh-chi-tiet/quan-an-ngon-18-phan-boi-chau-19-4892.JPG">
                                </div>

                                <div class="item">
                                    <img src="http://cdn.pasgo.vn/anh-chi-tiet/quan-an-ngon-18-phan-boi-chau-16-4893.JPG">
                                </div>

                                <div class="item">
                                    <img src="http://cdn.pasgo.vn/anh-chi-tiet/quan-an-ngon-18-phan-boi-chau-7-4894.JPG">
                                </div>

                                <div class="item">
                                    <img src="http://cdn.pasgo.vn/anh-chi-tiet/quan-an-ngon-18-phan-boi-chau-2-4895.jpg">
                                </div>
                            </div>

                            <!-- Left and right controls -->
                            <a class="left carousel-control" href="#myCarousel-restaurant" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel-restaurant" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>

                        <div class="content-infor shadow-outside">
                            <div class="highlight-infor">
                                <h3 style="font-weight: bold; color: #cc0000">ĐIỂM ĐẶC TRƯNG - AO QUÁN</h3>
                                <p>
                                    <strong>Loại hình ẩm thực: </strong>
                                    Gọi món truyền thống, cafe
                                </p>

                                <p>
                                    <strong>Món đặc sắc: </strong>
                                    Ếch rang muối, Gà quê nướng, chão chuộc nướng, trạch đồng chiên giòn, nõn đuôi bò, lẩu trê đồng hoa chuối…
                                </p>

                                <p>
                                    <strong>Giá trung bình/người (*): </strong>
                                    180.000 – 210.000 VNĐ
                                </p>

                                <p>
                                    <strong>Không gian:</strong><br/>

                                        - Phong cách đồng quê lãng mạn, độc đáo<br/>

                                        - Sức chứa 200 khách
                                </p>

                                <p>
                                    <strong>Chỗ để ô tô: </strong>Không
                                </p>

                                <p>
                                    <strong>Điểm đặc trưng khác:</strong><br/>
                                    Những món ăn đồng quê độc đáo và tươi sống 100%, nguyên liệu được nhập về từ các vùng quê.
                                </p>

                                <hr/>
                                <p style="font-size: 12px">
                                    (*) Mức giá trung bình dựa theo gợi ý của nhà hàng và chưa giảm giá khi đặt chỗ qua PASGO
                                </p>
                            </div>

                            <div class="read-more">
                                <h4>Ao quán Đông Tác- Chốn hẹn của những người quen</h4>

                                <p>
                                    Hà Thành xô bồ dân tứ xứ đổ về, kẻ Trung, người Bắc, ai ra đi cũng mang theo trong mình tình quê hương, tình bạn bè, anh em làm thứ vốn liếng dắt thân lập nghiệp. Khi thứ chân tình nồng hậu của người quê, đất cũ đôi khi bị lớp bụi của tiền bạc, lo toan phủ mờ, những lúc thấy mệt mỏi và nao nao ấy, anh em lại rủ nhau về Ao Quán, ngồi dưới gốc chuối, rặng dừa để chén tạc chén thù, chia ngọt sẻ bùi câu chuyện bôn ba nơi đất khách.
                                </p>
                                
                                <img src="http://cdn.pastaxi-manager.onepas.vn/content/uploads/articles/aoquan/nha-hang-ao-quan-ngo-19-dong-tac-1.jpg">
                                <p style="text-align: center"><span style="font-size: 12px">Ao Quán Đông Tác – Chốn hẹn của những người quen </span></p>

                                <p>Đón khách vào cổng nhỏ bằng gạch thô cũ là ao nước trong mát nằm dưới bóng chuối, bóng hoa, bóng lu vại. Khách không khỏi tò mò mà ngước nhìn lên những gác 2 gác 3 như chiếc chòi canh ao đang chật kín người, tiếng cười nói, tiếng zô, tiếng chén sành chạm nhau tưởng như đang lạc vào một bữa cỗ quê đầy háo hức.</p>

                                <img src="http://cdn.pastaxi-manager.onepas.vn/content/uploads/articles/aoquan/nha-hang-ao-quan-ngo-19-dong-tac-3.jpg">
                                <p style="text-align: center"><span style="font-size: 12px">Quán nằm khuất mình trong ngõ nhỏ giữa phố nhưng luôn đông khách</span></p>

                                <p>Nhưng đừng để sự thú vị của không gian khiến bạn choáng ngợp. Hãy giữ “cái đầu lạnh” để không bị những cánh hồng, cánh sen đang dập dìu vỗ ve dưới chân như mối tình thơ thuở quê nhà hay những chùm đèn bằng nơm úp cá tuổi thơ khiến bước chân bạn lỡ nhịp. Đôi khi, vào những dịp đặc biệt, còn có cả tiếng ghi ta gỗ bập bùng, những khúc hát mộc mạc, giản dị như chính không gian khiến thực khách mỉm cười.</p>

                                <h4>Thông tin liên hệ</h4>
                                <p><strong>Nhà hàng Ao Quán - Số 18 Ngõ 19 Đông Tác, Phường Kim Liên, Quận Đống Đa, Hà Nội</strong></p>


                                <div class="fb-like" data-href="http://localhost:8080/AnGiProject/restaurant/view" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
                            </div>
                        </div>

                        <div class="fb-comments" data-href="http://localhost:8080/AnGiProject/restaurant/view" data-numposts="5"></div>

                        <hr/>

                        <div class="shadow-outside" style="padding: 10px">
                            <h3>Bản đồ</h3>
                            <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script>
                            <div style='overflow:hidden;height:440px;width:100%;'>
                                <div id='gmap_canvas' style='height:440px;width:100%;'></div>
                                <div>
                                    <small><a href="http://embedgooglemaps.com">embed google maps</a></small>
                                </div>
                                <div>
                                    <small><a href="https://privacypolicygenerator.info">privacy policy example</a></small>
                                </div>
                                <style>#gmap_canvas img{max-width:none!important;background:none!important}</style>
                            </div>
                            <script type='text/javascript'>
                                function init_map(){
                                    var myOptions = {zoom:13,center:new google.maps.LatLng(21.022951879558534,105.81340667091669),mapTypeId: google.maps.MapTypeId.ROADMAP};
                                    map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);
                                    marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(21.022951879558534,105.81340667091669)});
                                    infowindow = new google.maps.InfoWindow({content:'<strong>Ao quán</strong><br>Số 18 Ngõ 19 Đông Tác, Phường Kim Liên, Quận Đống Đa, Hà Nội<br>'});
                                    google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);
                                }google.maps.event.addDomListener(window, 'load', init_map);
                            </script>
                        </div>
                    </div>
                    <div id="price" class="tab-pane fade">
                        <img src="http://cdn.pastaxi-manager.onepas.vn/Content/Uploads/Prices/aoquan/nha-hang-ao-quan-header.jpg">
                    </div>


                    <div style="margin: 25px 0 25px -15px">
                        <div class="title-content">
                            <div class="title-row">
                                <div class="col-md-12">
                                    <h3>Có thể bạn quan tâm</h3>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <hr class="underTit"/>
                            </div>
                        </div>
                        <ul class="item-content item-cat">
                            <?php
                            for($i=0; $i<4; $i++){
                                ?>
                                <li class="col-md-3">
                                    <a style="display: block; position: relative" class="img-item" href="">
                                        <img src="http://cdn.pasgo.vn/anh-diem-den/nha-hang-ao-quan-ngo-19-dong-tac-avatarjpg-5138.jpg">
                                        <div class="item-infor">
                                            <label class="item-name item-name-sm">Ao quán</label>
                                <span class="rate-star">
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star filled" aria-hidden="true"></i>
                                    <i class="fa fa-star" aria-hidden="true"></i>
                                </span>
                                <span class="rate-dollar">
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                    <i class="fa fa-dollar" aria-hidden="true"></i>
                                </span>
                                            <label class="item-address item-address-sm">18 Ngõ 19 Đông Tác, Quận Đống Đa</label>
                                        </div>
                                    </a>

                                    <div class="category-itemdetail" style="border: 1px solid #e0e0e0; text-align: center">
                                        <p class="sale-content">Giảm <strong>20%</strong></p>
                                        <p class="quick-description">Gọi món Việt ba miền</p>
                                        <button class="place">Đặt chỗ ngay</button>
                                    </div>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>