<div class="title-content">
    <div class="title-row">
        <div class="col-md-6">
            <h3><?php echo $title; ?></h3>
        </div>
        <div class="col-md-6">
            <a class="small-tit" href="<?php echo $urlAllView; ?>">Xem tất cả <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
        </div>
    </div> 
    <div class="col-md-12">
        <hr class="underTit"/>
    </div>
</div>    
<ul class="item-content">
<?php foreach($items as $item){ ?>
    <li class="col-md-3">
        <a style="display: block; position: relative" class="img-item" href="<?php echo $this->uriutils->BuildViewResUrl($item->restaurantID); ?>">
            <img src="<?php echo $item->imageUrl != '' ? $item->imageUrl : 'http://cdn.pasgo.vn/anh-diem-den/nha-hang-ao-quan-ngo-19-dong-tac-avatarjpg-5138.jpg'; ?>">
            <div class="item-infor">
                <label class="item-name"><?php echo $item->nameRe; ?></label>
                <span class="rate-star">
                    <?php for($j=0; $j< 5; $j++){?>
                    <?php if ($j < $item->rateRe){?>
                    <i class="fa fa-star filled" aria-hidden="true"></i>
                    <?php }else {?>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <?php }?>                                    
                    <?php }?>
                </span> 
                <label class="item-address"><?php echo $item->address; ?></label>
            </div>
        </a> 
        <div style="border: 1px solid #e0e0e0; text-align: center">
            <p class="sale-content">Giảm <strong><?php echo $item->discount; ?>%</strong></p>
            <p class="quick-description"><?php echo $this->xulychuoi->GetTitleNew( $item->descriptionRes); ?></p>
            <a href="<?php echo $this->uriutils->BuildViewResUrl($item->restaurantID); ?>">
                <button class="place">Đặt chỗ ngay</button>
            </a>
        </div>
    </li>
<?php } ?>
</ul>