<div class="title-content">
    <div class="title-row">
        <div class="col-md-12">
            <h3>Có thể bạn quan tâm</h3>
        </div>
    </div>

    <div class="col-md-12">
        <hr class="underTit"/>
    </div>
</div>
<ul class="item-content item-cat">
    <?php
    foreach($relations as $item){
        ?>
        <li class="col-md-3 col-sm-6">
            <a style="display: block; position: relative" class="img-item" href="<?php echo $this->uriutils->BuildViewResUrl($item->restaurantID); ?>">
                <img src="<?php echo $item->imageUrl != '' ? base_url().$item->imageUrl : base_url().'img/no-image.jpg'; ?>">
                <div class="item-infor">
                    <label class="item-name item-name-sm"><?php echo $item->nameRe; ?></label>
                    <span class="rate-star">
                        <?php for($j=0; $j< 5; $j++){?>
                        <?php if ($j < $item->rateRe){?>
                        <i class="fa fa-star filled" aria-hidden="true"></i>
                        <?php }else {?>
                        <i class="fa fa-star" aria-hidden="true"></i>
                        <?php }?>                                    
                        <?php }?>     
                    </span>
                    
                    <label class="item-address item-address-sm"><?php echo $item->address; ?></label>
                </div>
            </a>

            <div class="category-itemdetail" style="border: 1px solid #e0e0e0; text-align: center">
                <p class="sale-content">Giảm <strong><?php echo $item->discount; ?>%</strong></p>
                <p class="quick-description"><?php echo $this->xulychuoi->GetTitleNew( $item->descriptionRes); ?></p>
                <a href="<?php echo $this->uriutils->BuildViewResUrl($item->restaurantID); ?>">
                    <button class="place">Đặt chỗ ngay</button>
                </a>
            </div>
        </li>
        <?php
    }
    ?>
</ul>