<link rel="stylesheet" href="<?php echo base_url() ?>css/user.css">

<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            
            <?php $this->load->view('site/user/profile/profile_image.phtml'); ?>
            
            <ul class="profile-sidebar">
                <li><a href="<?php echo base_url(); ?>user/change_Password"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</a></li>

                <?php if ($userData[0]['authorityUser'] == 2) {
                    ?>
                    <li><a href="<?php echo base_url(); ?>restaurant/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                    <li><a href="<?php echo base_url(); ?>Restaurant/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                    <li><a href="<?php echo base_url(); ?>Restaurant/restaurant_menu"><i class="fa fa-usd" aria-hidden="true"></i> Bảng Menu</a></li>
                    <li><a href="<?php echo base_url(); ?>booking/manageReservation"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>                
                    <?php
                }
                ?>           
                <li><a href="<?php echo base_url(); ?>booking/viewBooking"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>           
                <li class="active"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</li>

                <li><a href="<?php echo base_url(); ?>user/sign_out"><i class="fa fa-power-off" aria-hidden="true"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">

            <h1>Đổi mật khẩu</h1>
            <?PHP echo form_open('user/change_Password', 'class="edit-user" '); ?>
            <!-- <form class="edit-user" action="change_Password" method="GET"> -->
            <ul>
                <li>
                    <label>Mật khẩu cũ:</label> <input name="opassword" type="password" value="">
                    <span class="text-danger"><?php echo form_error('opassword'); ?></span>
                </li>
                <li>
                    <label>Mật khẩu mới:</label> <input name="npassword" type="password" value="">
                    <span class="text-danger"><?php echo form_error('npassword'); ?></span>
                </li>
                <li>
                    <label>Nhập lại mật khẩu:</label> <input name="cpassword" type="password" value="">
                    <span class="text-danger"><?php echo form_error('cpassword'); ?></span>
                </li>
                <li>
                    <label></label>
                    <input type="submit" name="btn" value="Cập nhật">
                </li>
            </ul>
            <?php echo form_close(); ?>
            <?php echo $this->session->flashdata('msg'); ?>
        </div>
    </div>
</div>