<link rel="stylesheet" href="<?php echo base_url()?>css/user.css">

<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="col-md-3">
            <table class="profile-stt">
                <tr>
                    <td><img src="http://cdn.pasgo.vn/images/Profile/no_avatar.png"></td>
                    <td>
                        <p>ID ĂnGì: <strong><?php echo $this->session->userdata("ID"); ?></strong></p>
                        <p>ĐT: <strong><?php echo $this->session->userdata("phone"); ?></strong></p>
                    </td>
                </tr>

                <tr>
                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
                    <td></td>
                </tr>
            </table>
            <ul class="profile-sidebar">
                <li class="active"><i class="fa fa-user" aria-hidden="true"></i> Thông tin tài khoản</li>
            
            <?php if ($userData[0]['authorityUser'] == 2){
            ?>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_banner"><i class="fa fa-picture-o" aria-hidden="true"></i> Banner nhà hàng</a></li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_infor"><i class="fa fa-wpforms" aria-hidden="true"></i> Thông tin nhà hàng</a></li>
                <li><a href="<?php echo base_url(); ?>restaurant/restaurant_price"><i class="fa fa-usd" aria-hidden="true"></i> Bảng giá</a></li>
                <li><a href="<?php echo base_url(); ?>booking/manageReservation"><i class="fa fa-cogs" aria-hidden="true"></i> Quản lý đặt chỗ</a></li>                
            <?php
            }
            ?>         
                <li><a href="<?php echo base_url(); ?>booking/viewBooking"><i class="fa fa-cutlery" aria-hidden="true"></i> Lịch sử đặt chỗ</a></li>
          
                <li><a href="<?php echo base_url(); ?>user/change_Password"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Đổi mật khẩu</a></li>

                <li><a href="<?php echo base_url(); ?>user/sign_out"></i> Thoát</a></li>
            </ul>
        </div>

        <div class="col-md-9">
            <?php if ($userData[0]['authorityUser'] == 1){
            ?>
                <h1>Thông tin thực khách</h1>
            <?php
            }
            ?>
            <?php if ($userData[0]['authorityUser'] == 2){
            ?>
                <h1>Thông tin chủ nhà hàng</h1>
            <?php
            }
            ?>
            
            <form class="edit-user" method="post" action="user">
                <ul>
                    <li>
                        <label>Ngày lập:</label> <input type="text" value="<?php echo $userData[0]['dateCreateUser']; ?>" disabled>
                    </li>
                    <li>
                        <label>Họ:</label> <input type="text" name="lname" value="<?php echo $userData[0]['lastNameUser'];
                ?>">
                        <span class="text-danger"><?php echo form_error('lname'); ?></span>
                    </li>
                    <li>
                        <label>Tên:</label> <input type="text" name="fname" value="<?php echo $userData[0]['firstNameUser'];
                ?>">
                    </li>
                    <li>
                        <label>Email:</label> <input type="text" name="email" value="<?php echo $userData[0]['emailUser']; ?>">
                    </li>

                    <li>
                        <label>Ngày sinh:</label> <input type="date" name="dob" value="<?php echo $userData[0]['dateOfBirthUser']; ?>" max="2015-01-01" min="1950-01-01"/>
                    </li>
                    <li>
                        <label>Giới tính:</label> 
                        <?php if ($userData[0]['genderUser'] == 1)
                        {
                            ?>
                           
                                <input type="radio" name="gender" value="1" checked > Nam
                                <input style="margin-left: 100px;" type="radio" name="gender" value="0" > Nữ
                            
                        <?php
                        }
                         ?>

                         <?php if ($userData[0]['genderUser'] == 0)
                        {
                            ?>
                           
                                <input type="radio" name="gender" value="1" > Nam
                                <input style="margin-left: 100px;" type="radio" name="gender" value="0" checked > Nữ
                            
                        <?php
                        }
                         ?>
                    </li>
            <?php if ($userData[0]['authorityUser'] == 2){
            ?>

                    <li>
                        <label>Địa chỉ:</label> <input type="text" name="address" value="<?php 
                        echo $addressData[0]['address'] ;
                        
                ?>">
                    </li>

                    <li>
                        <label>Tỉnh thành:</label> 
                        <select name="province" size="1">
                            <?php 
                                foreach ($province as $key => $row)
                                {
                                   if($addressData[0]['provinceID'] == $row['provinceID']){
                                        echo '<option value="' . $row['provinceID'] . '" selected >' .$row['typePro'].' '. $row['namePro'] . '</option>';
                                   }
                                   else{
                                        echo '<option value="' . $row['provinceID'] . '">' .$row['typePro'].' '. $row['namePro'] . '</option>';
                                   }
                                }
                            ?>
                        </select>

                    </li>
                    <li>
                        <label>Quận huyện:</label> 
                        <select name="district" size="1">
                            <?php 
                                foreach ($district as $key => $row)
                                {
                                   if($addressData[0]['districtid'] == $row['districtid']){
                                        echo '<option value="' . $row['districtid'] . '" selected >' .$row['typeDis'].' '. $row['nameDis'] . '</option>';
                                   }
                                   else{
                                        echo '<option value="' . $row['districtid'] . '">' .$row['typeDis'].' '. $row['nameDis'] . '</option>';
                                   }
                                   
                                }
                            ?>
                        </select>
                    </li>
                    <li>
                        <label>Khu vực:</label>
                        <select name="ward" size="1">
                            <?php 
                                foreach ($ward as $key => $row)
                                {   
                                   if($addressData[0]['wardid'] == $row['wardid']){
                                        echo '<option value="' . $row['wardid'] . '" selected >' .$row['typeWard'].' '. $row['nameWard'] . '</option>';
                                   }
                                   echo '<option value="' . $row['wardid'] . '">' .$row['typeWard'].' '. $row['nameWard'] . '</option>';
                                }
                            ?>
                        </select>                        
                    </li>


            <?php
            }
            ?>                     

                    <li>
                        <label></label>
                        <input type="submit" value="Cập nhật">
                    </li>
                </ul>
            </form>
            <?php echo $this->session->flashdata('msg'); ?>
        </div>
    </div>
</div>