<?php echo form_open_multipart('image/changeAvatar'); ?>
<table class="profile-stt">
    <tr>
        <td><img id="avatar" src="<?php echo base_url($this->session->userdata("avatarSes")); ?>" alt="banner"></td>
        <td>
            <p>ID ĂnGì: <strong><?php echo $this->session->userdata("ID"); ?></strong></p>
            <p>ĐT: <strong><?php echo $this->session->userdata("phone"); ?></strong></p>
        </td>
    </tr>

    <tr>
<!--                    <td style="padding: 0 8px 20px"><button>Chọn ảnh</button></td>
        <td></td>-->
        <td style="text-align: center">
            <label class = "select-file-btn">
                <input type="file" name="avatarFile" onchange="readURL(this);" />
                Tai anh
            </label>
        </td>
        <td></td>
    </tr>
</table>
<span class="text-danger"><?php
        if (isset($error)) {
            echo $error;
        }
        ?>
</span>
<?php
echo form_close();
if (isset($success_msg)) {
    echo $success_msg;
}
?>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#avatar')
                        .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
            // enable submit button
            $("#btnProfile").removeAttr('disabled');
        }
    }
</script>