<div class="panel panel-default">
  <!-- Default panel contents -->
    <div class="panel-heading">
        <h2>Chi tiết đơn hàng</h2>
    </div>
    <div class="panel-body">
        <a style="margin-bottom: 15px" class="btn btn-default" href="<?php echo base_url()?>admin/booking" role="button"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Quay về</a>

        <form method="POST" action="">
            <div class="form-group">
            <label for="memName">Mã</label>
            <input disabled="disabled" type="text" class="form-control" value="<?php echo isset($bookingID) ? $bookingID : ''; ?>"> 
        </div>
        <div class="form-group"> 
            <label for="dateCreateBo">Ngày tạo</label>
            <input disabled="disabled" type="text" class="form-control" value="<?php echo isset($dateCreateBo) ? $dateCreateBo : ''; ?>"> 
        </div> 
        <div class="form-group"> 
            <label for="quantityMember">Số người</label>
            <input disabled="disabled" type="text" class="form-control" value="<?php echo isset($quantityMember) ? $quantityMember : ''; ?>"> 
        </div>   
        <div class="form-group"> 
            <label for="dateCreateBo">Ăn vào thời gian</label>
            <input disabled="disabled" type="text" class="form-control" value="<?php echo isset($dateBooking) ? $dateBooking : ''; ?>"> 
        </div> 
        <div class="form-group"> 
            <label for="restaurantName">Tên quán</label>
            <input disabled="disabled" type="text" class="form-control" value="<?php echo isset($restaurantName) ? $restaurantName : ''; ?>"> 
        </div> 
        <div class="form-group"> 
            <label for="userName">Người đặt</label>
            <input disabled="disabled" type="text" class="form-control" value="<?php echo isset($userName) ? $userName : ''; ?>"> 
        </div> 
        <div class="form-group"> 
            <label for="commentBo">Ghi chú</label>
            <textarea disabled="disabled" id="commentBo" name="commentBo" type="text" class="form-control" ><?php echo isset($commentBo) ? $commentBo : ''; ?></textarea>
        </div>       
        <div class="form-group"> 
            <label for="$statusBo">Trạng thái</label> 
            <select disabled="disabled" id="statusBo" name="statusBo" class="form-control">
              <option id="0" value="0" <?php if(isset($statusBo) && $statusBo == 0){ echo 'selected="selected"';} else {echo '';} ?> >Mới đặt</option>
              <option id="1" value="1" <?php if(isset($statusBo) && $statusBo == 1){ echo 'selected="selected"';} else {echo '';} ?> >Đã xử lý</option>
              <option id="1" value="2" <?php if(isset($statusBo) && $statusBo == 2){ echo 'selected="selected"'; } else {echo '';} ?>>Hoàn thành</option>
            </select>
        </div>
        
    </form>
  </div> 
</div>
   