<div class="form-group">    
<div class="col-lg-12"> 
    <label for="addressID">Địa chỉ</label> 
    <select id="addressID" name="addressID" class="form-control">        
      <option id="" value="0" selected="selected">--chọn địa chỉ--</option>  
      <?php foreach($address as $adr){?>
         <option id="<?php echo $adr->addressID; ?>" value="<?php echo $adr->addressID; ?>" <?php if(isset($addressID) && $addressID == $adr->addressID){ echo 'selected="selected"';} else {echo '';} ?> ><?php echo $adr->address; ?></option>
      <?php } ?>
    </select>
</div>  
<div class="col-lg-6"> 
    <label for="userMail">latitudeRe</label>
    <input type="text" class="form-control" id="latitudeRe"  name="latitudeRe"  value="<?php echo isset($latitudeRe) ? $latitudeRe : ''; ?>"> 
</div>
<div class="col-lg-6"> 
    <label for="userMail">longitudeRe</label>
    <input type="text" class="form-control" id="longitudeRe"  name="longitudeRe"  value="<?php echo isset($longitudeRe) ? $longitudeRe : ''; ?>"> 
</div> 
<div class="col-lg-12"> 
    <label for="userMail">otherPoints</label>
    <input type="text" class="form-control" id="otherPoints"  name="otherPoints"  value="<?php echo isset($otherPoints) ? $otherPoints : ''; ?>"> 
</div>     
</div>     