<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <h2>Danh sách tài khoản</h2>
  </div>
  <div class="panel-body">
  <div class="col-lg-12">
    <form method="POST" action=""> 
        <div class="form-group">                 
            <select id="userLevel" name="userLevel" class="form-control">
              <option id="0" value="0" <?php if(isset($level) && $level == '0'){ echo 'selected="selected"';} else {echo '';} ?> >Thực khách</option>
              <option id="1" value="1" <?php if(isset($level) && $level == '1'){ echo 'selected="selected"'; } else {echo '';} ?>>Nhà hàng</option>
            </select>
        </div> 
    </form> 
  </div> 
  <!-- Table -->
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
<!--            <th>Tên đăng nhập</th>-->
            <th>Họ & tên</th>
            <th>Email</th>
            <th>Địa chỉ</th>
            <th>Trạng thái</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($rows > 0){ ?>
        <?php foreach ($result as $user) {?>
        <tr>
            <td><?php echo $user->userID; ?></td>
<!--            <td>--><?php //echo $user->userName; ?><!--</td>-->
            <td><?php echo $user->memName; ?></td>
            <td><?php echo $user->userMail; ?></td>
            <td><?php echo $user->address; ?></td>
            <td class="text-center"><?php echo $user->userActived == 1 ? 'Hoạt động' : 'Chưa kích hoạt'; ?></td>
            <td class="text-center">
            <a class="btn btn-info" href="<?php echo base_url()?>admin/edit_eater/<?php echo $user->userID; ?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Xem</a>
            <a class="btn btn-danger" onclick="return userModule.delete('<?php echo $user->userName; ?>');" href="<?php echo base_url()?>admin/delete_eater/<?php echo $user->userID; ?>"><i class="fa fa-trash-o" aria-hidden="true"></i> Xóa</a>   
            </td>
        </tr>
        <?php } ?>
        <?php } ?>
    </tbody>
  </table>
  </div>
      
</div>
<script type="text/javascript">
    window.userModule = window.userModule || {};
    
    userModule.delete = userModule.delete || function(name){
        if (confirm('Xóa tài khoản ' + name + '?'))
            return true;
        return false;
    }
    
    $(document).ready(function(){
        $('#userLevel').change(function($this){
            location.href = '<?php echo base_url()?>admin/eater/'+ $(this).val();
        })
    })
</script>