<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>
        <?php $this->load->helper('url'); ?>
        <div class="topdisplay-item" style="display: table; width: 100%">
            <div class="title-content">
                <div class="title-row">
                    <div class="col-md-12">
                        <h3>nhà hàng</h3>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>
            </div>

            <div class="sidebar col-md-2">
                <div class="sidebar-content">
                    <h4>Danh mục</h4>
                    <ul class="sidebar-list">
                        <?php
                        foreach ($categoriesData as $key => $row) {
                            ?>
                            <li><a href="<?php echo base_url(); ?>Category/index/1/<?php echo $row['categoryOfResID']; ?>"><?php echo $row['nameCOR']; ?></a></li>        
                            <?php
                        }
                        ?>
                    </ul>
                </div>

                <div class="sidebar-content">
                    <h4>Quận/Huyện</h4>

                    <div class="form-group">
                        <select class="form-control" ID="district" size="1">
                            <option value="" >chọn quận huyện</option>
                            <?php
                            foreach ($districtData as $key => $row) {
                                echo '<option value="' . $row['districtid'] . '">' . $row['typeDis'] . ' ' . $row['nameDis'] . '</option>';
                            }
                            ?>
                        </select>
                    </div>

                </div>
            </div>

            <div class="col-md-10">
                <ul class="item-content item-cat">
                    <?php
                    $j = 0;

                    foreach ($resData as $key => $row) {
                        ?>
                        <li class="col-md-3">
                            <a style="display: block; position: relative" class="img-item" href="">
                                <img src="http://cdn.pasgo.vn/anh-diem-den/nha-hang-ao-quan-ngo-19-dong-tac-avatarjpg-5138.jpg">
                                <div class="item-infor">
                                    <label class="item-name item-name-sm"><?php echo $row['nameRe']; ?></label>
                                    <span class="rate-star">
                                        <?php
                                        $i = 1;
                                        for ($i; $i <= $rate[$j]['avgrate']; $i++) {
                                            ?>
                                            <i class="fa fa-star filled" aria-hidden="true"></i>

                                            <?php
                                            if (($i + 0.25 <= $rate[$j]) && ($i + 0.75 > $rate[$j])) {
                                                ?>
                                                <i class="fa fa-star-half-o filled" aria-hidden="true"></i>

                                                <?php
                                                $i++;
                                            }
                                        }
                                        ?>

                                        <?php
                                        for ($k = 0; $k <= (5 - $i); $k++) {
                                            ?>
                                            <i class="fa fa-star " aria-hidden="false"></i>
                                            <?php
                                        }

                                        $j++;
                                        ?>  

                                    </span>
                                    <span class="rate-dollar">
                                        <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                        <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                        <i class="fa fa-dollar filled" aria-hidden="true"></i>
                                        <i class="fa fa-dollar" aria-hidden="true"></i>
                                        <i class="fa fa-dollar" aria-hidden="true"></i>
                                    </span>
                                    <label class="item-address item-address-sm"><?php echo $row['address']; ?></label>
                                </div>
                            </a>
                            <div class="category-itemdetail" style="border: 1px solid #e0e0e0; text-align: center">
                                <p class="sale-content">Giảm <strong><?php echo $row['discount']; ?>%</strong></p>
                                <p class="quick-description"><?php echo $row['latitudeRe']; ?></p>
                                <?php echo form_open('booking/reserve/' . $row['restaurantID']); ?>
                                <input type="submit" class="place" value="Đặt chỗ ngay" />
                                <?php echo form_close(); ?> 
                            </div>
                        </li>
                        <?php
                    }
                    ?>
                </ul>
            </div>
        </div>
        <!-- <?php echo $pagination; ?> -->
        <div style="text-align: center">
            <ul class="pagination">
                <?php
                for ($k = 1; $k <= $pages; $k++) {

                    echo '<li><a href="' . base_url() . 'Category/index/' . $type . '/' . $ID . '/' . $k . '">' . $k . '</a></li>';
                }
                ?>

                <!--                 <li><a href="">1</a></li>
                                <li><a href="">2</a></li>
                                <li><a href="">3</a></li>
                                <li><a href="">4</a></li>
                                <li><a href="">5</a></li> -->
            </ul>
        </div>
    </div>
</div>
<script type="text/javascript">

    $('#district').change(
            function () {
                var e = document.getElementById("district");
                var ID = e.options[e.selectedIndex].value;
                console.log(ID);
                window.location.replace("<?php echo base_url(); ?>Category/index/2/" + ID);
            }
    );

</script>