<div class="container">
    <div class="row">
        <div class="breadcrumb"></div>

        <div class="topdisplay-item" style="display: table">
            <div class="title-content">
                <div class="title-row">
                    <div class="col-md-12">
                        <h3>Ẩm thực</h3>
                    </div>
                </div>

                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>
            </div>

            <div class="sidebar col-md-2">
                <div class="sidebar-content">
                    <h4>Danh mục</h4>
                    <ul class="sidebar-list">
                        <li><a href="">Nhà hàng</a></li>
                        <li><a href="">Buffet</a></li>
                        <li><a href="">Lẩu & Nướng</a></li>
                        <li><a href="">Hải sản</a></li>
                        <li><a href="">Nhật - Hàn</a></li>
                        <li><a href="">Ăn nhậu</a></li>
                    </ul>
                </div>

                <div class="sidebar-content">
                    <h4>Quận/Huyện</h4>
                    <ul class="sidebar-list">
                        <li><a href="">Ba Đình</a></li>
                        <li><a href="">Hoàn Kiếm</a></li>
                        <li><a href="">Thanh Xuân</a></li>
                        <li><a href="">Hai Bà Trưng</a></li>
                        <li><a href="">Đống Đa</a></li>
                        <li><a href="">Cầu Giấy</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-md-10">
                <ul class="item-content item-cat">
                    <?php
                    $limit = 0;
                    foreach ($food as $row) {
                        if ($limit == $limitDisplay) {
                            break;
                        }
                        ?>
                        <li class="col-md-3">
                            <a style="display: block; position: relative" class="img-item" href="">
                                <img src="<?php echo $row->addressImage; ?>">
                            </a>
                            <span>Name: <?php echo $row->nameFo; ?></span><br />
                            <span>Description: <?php echo $row->desciptionFo; ?></span><br />
                            <span>Category: <?php echo $row->typeFo; ?></span>
                        </li>
                        <?php
                        $limit ++;
                    }
                    ?>
                </ul>
            </div>
        </div>

        <div style="text-align: center">
            <ul class="pagination">
                <li><a href="">1</a></li>
                <li><a href="">2</a></li>
                <li><a href="">3</a></li>
                <li><a href="">4</a></li>
                <li><a href="">5</a></li>
            </ul>
        </div>
    </div>
</div>