<div class="container">
    <div class="row"> 
        <div class="topdisplay-item">
            <div class="title-content" style="margin-top: 20px;">
                <div class="title-row">
                    <div class="col-md-6">
                        <h3><?php echo $categoryName; ?></h3>
                    </div>  
                </div> 
                <div class="col-md-12">
                    <hr class="underTit"/>
                </div>  
            </div>  
            <ul class="item-content">
            <?php foreach($items as $item){ ?>
                <li class="col-md-4">
                    <a style="display: block; position: relative" class="img-item" href="<?php echo $this->uriutils->BuildViewNewsUrl($item->newsID); ?>">
                        <img style="max-height: 223px;" src="<?php echo $item->imageNews != '' ? $item->imageNews : 'http://cdn.pasgo.vn/anh-tin-tuc-resize/400/pasgo-nang-cap-va-cau-chuyen-de-men-phieu-luu-ky-54.jpg'; ?>">
                    </a>

                    <div style="text-align: center">     
                        <h4 class="news-title"><a href=""><?php echo $this->xulychuoi->GetTitleNew( $item->titleNews, 60); ?></a></h4>
                        <p class="news-desc"><?php echo $this->xulychuoi->GetIntroText( $item->contentNews, 200); ?></p>
                    </div>
                </li>
            <?php } ?>
            </ul>
        </div>
    </div>
    <div class="row">
        <div style="text-align: center">
            <?php echo $pagination; ?>
        </div>
</div>
</div>